// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © goodgains


//@version=5
indicator("3MA Average", overlay = true)

// @keywords: 3ma-average, triple-moving-average, three-moving-average, moving-average-composite, averaged-moving-averages, configurable-ma-lengths, multi-type-moving-average, ema, sma, wma, vwma, hull-moving-average, price-crossover, crossunder-signals, buy-sell-signals, alternating-signals, label-markers, trend-following, close-vs-average, entry-signals

malength1 = input.int(9, title = 'MA 1', group = 'Settings', inline = '1')
malength2 = input.int(20, title = 'MA 2', group = 'Settings', inline = '2')
malength3 = input.int(50, title = 'MA 3', group = 'Settings', inline = '3')

ma_type1 = input.string("EMA", title = '',
 options = ['SMA', 'EMA', 'WMA', 'HMA', 'VWMA'], group = 'Settings', inline = '1')
ma_type2 = input.string("EMA", title = '',
 options = ['SMA', 'EMA', 'WMA', 'HMA', 'VWMA'], group = 'Settings', inline = '2')
ma_type3 = input.string("EMA", title = '',
 options = ['SMA', 'EMA', 'WMA', 'HMA', 'VWMA'], group = 'Settings', inline = '3')


 // calc ma
float ma_value1 = switch ma_type1
    "EMA" => ta.ema(close, malength1)
    "SMA" => ta.sma(close, malength1)
    "WMA" => ta.wma(close, malength1)
    "VWMA" => ta.vwma(close, malength1)
    "HMA" => ta.hma(close, malength1)
    => ta.sma(close, malength1)

float ma_value2 = switch ma_type2
    "EMA" => ta.ema(close, malength2)
    "SMA" => ta.sma(close, malength2)
    "WMA" => ta.wma(close, malength2)
    "VWMA" => ta.vwma(close, malength2)
    "HMA" => ta.hma(close, malength2)
    => ta.sma(close, malength2)

float ma_value3 = switch ma_type3
    "EMA" => ta.ema(close, malength3)
    "SMA" => ta.sma(close, malength3)
    "WMA" => ta.wma(close, malength3)
    "VWMA" => ta.vwma(close, malength3)
    "HMA" => ta.hma(close, malength3)
    => ta.sma(close, malength3)


three_maavg = (ma_value1 + ma_value2 + ma_value3) / 3

plot(ma_value1, title = 'MA 1 ', color = color.blue, linewidth = 2, display = display.none)
plot(ma_value2, title = 'MA 2', color = color.blue, linewidth = 2, display = display.none)
plot(ma_value3, title = 'MA 3', color = color.blue, linewidth = 2, display = display.none)


plot(three_maavg, title = '3MA Avg', color = color.blue)



var show_signals = true
var int last_signal = 0
bull_cross = ta.crossover(close, three_maavg)
bear_cross = ta.crossunder(close, three_maavg)

long_entry = bull_cross and last_signal[1] != 1
short_entry = bear_cross and last_signal[1] != -1

last_signal := bull_cross ? 1 : bear_cross ? -1 : last_signal[1]

plotshape(show_signals and long_entry ? math.min(low, three_maavg) - syminfo.mintick * 10 : na,
 style=shape.labelup, editable=false, text= "BUY", textcolor=color.white, location= location.belowbar,
 color=color.new(color.teal, 30), size=size.tiny)

plotshape(show_signals and short_entry ? math.max(high, three_maavg) - syminfo.mintick * 10 : na,
 style=shape.labeldown, editable=false, text='SELL', textcolor=color.white, location=location.abovebar,
 color=color.new(color.red, 30), size=size.tiny)


