// © goodgains
//@version=5

indicator(shorttitle='Bands Indicator', title='Bands Indicator', overlay=true)

// @keywords: bands-indicator, vwma, volume-weighted-moving-average, standard-deviation, deviation-bands, fibonacci-bands, fibonacci-ratios, support-levels, resistance-levels, upper-bands, lower-bands, mid-line, volatility-bands, price-envelope, sigma-bands, statistical-bands, r-levels, s-levels, mean-reversion-levels, mult-deviation

length = input.int(200, minval=1)
src = input(hlc3, title='Source')
mult = input.float(3.0, minval=0.001, maxval=50)
basis = ta.vwma(src, length)
dev = mult * ta.stdev(src, length)
upper_1 = basis + 0.236 * dev
upper_2 = basis + 0.382 * dev
upper_3 = basis + 0.5 * dev
upper_4 = basis + 0.618 * dev
upper_5 = basis + 0.764 * dev
upper_6 = basis + 1 * dev
lower_1 = basis - 0.236 * dev
lower_2 = basis - 0.382 * dev
lower_3 = basis - 0.5 * dev
lower_4 = basis - 0.618 * dev
lower_5 = basis - 0.764 * dev
lower_6 = basis - 1 * dev






p13 = plot(lower_1, color=color.new(color.white, 0), linewidth=1, title='S-1')
p14 = plot(lower_2, color=color.new(color.white, 0), linewidth=1, title='S-2')
p15 = plot(lower_3, color=color.new(color.white, 0), linewidth=1, title='S-3')
p16 = plot(lower_4, color=color.new(color.white, 0), linewidth=1, title='S-4')
p17 = plot(lower_5, color=color.new(color.white, 0), linewidth=1, title='S-5')
p18 = plot(lower_6, color=color.new(color.green, 0), linewidth=2, title='S-6')
plot(basis, color=color.new(color.fuchsia, 0), linewidth=2, title='Mid Line')

p1 = plot(upper_1, color=color.new(color.white, 0), linewidth=1, title='R-1')
p2 = plot(upper_2, color=color.new(color.white, 0), linewidth=1, title='R-2')
p3 = plot(upper_3, color=color.new(color.white, 0), linewidth=1, title='R-3')
p4 = plot(upper_4, color=color.new(color.white, 0), linewidth=1, title='R-4')
p5 = plot(upper_5, color=color.new(color.white, 0), linewidth=1, title='R-5')
p6 = plot(upper_6, color=color.new(color.red, 0), linewidth=2, title='R-6')




