//@version=5
indicator(title="Donchian Channels", shorttitle="DC", overlay=true, timeframe="", timeframe_gaps=true)
length = input.int(20, minval=1)


atr_value = ta.atr(14)
upper = ta.wma(ta.highest(length),length) + atr_value * 2
lower = ta.wma(ta.lowest(length),length) - atr_value * 2

basis = math.avg(upper, lower)
plot(basis, "Basis", color=#FF6D00)
u = plot(upper, "Upper", color=#2962FF)
l = plot(lower, "Lower", color=#2962FF)
fill(u, l, color=color.rgb(33, 150, 243, 95), title="Background")


buy = ta.crossunder(low, lower)
sell = ta.crossover(high, upper)


buy_color = input.color(#27a69b, title='Buy Color', inline='7', group='Signal Settings')
sell_color = input.color(#b63632, title='Sell Color', inline='7', group='Signal Settings')

show_signals = true

plotshape(show_signals and buy and math.sum(buy[1] == true ? 1 : 0,10) == 0 and barstate.isconfirmed ? lower - (syminfo.mintick * 20) : na, style=shape.labelup, editable=false, text= "Buy", textcolor=color.white, location= location.absolute, color=color.new(buy_color, 30), size=size.tiny)
plotshape(show_signals and sell and math.sum(sell[1] == true ? 1 : 0,10) == 0  and barstate.isconfirmed ? upper + (syminfo.mintick * 20) : na, style=shape.labeldown, editable=false, text='Sell', textcolor=color.white, location=location.absolute, color=color.new(sell_color, 30), size=size.tiny)