// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © atraderstoolbox

//@version=5
indicator("for_lavis25", overlay = true)

// bollinger band settings
bb_source   = input.source(close, title = 'Source', group = 'BB Settings')
bb_length   = input.int(10, title = 'Length', group = 'BB Settings')
bb_dev      = input.float(1.0, title = 'Deviation', group = 'BB Settings')

f_bb(src, length, mult) =>
    float basis = ta.sma(src, length)
    float dev = mult * ta.stdev(src, length)
    [basis, basis + dev, basis - dev]


[middle, upper, lower] = f_bb(bb_source, bb_length, bb_dev)

var int last_signal = na
var bool buy_signal = na
var bool sell_signal = na
buy_signal := ta.crossover(close,upper)
sell_signal := ta.crossunder(close,lower)
last_signal := buy_signal ? 1
 : sell_signal ? -1 
 : last_signal[1]


p_mid   = plot(middle, title = 'Middle', color = color.new(color.red,60), linewidth = 3, display = display.none)
p_lower = plot(lower, title = 'Lower', color = last_signal == 1 ? color.new(color.blue,50) : last_signal == -1 ? color.new(color.red,50) : color.gray)
p_upper = plot(upper, title = 'Upper', color = last_signal == 1 ? color.blue : last_signal == -1 ? color.red : color.gray)
fill(p_upper, p_lower, title = 'Fill', color = last_signal == 1 ? color.new(color.green,80) : last_signal == -1 ? color.new(color.red,80) : color.gray)
barcolor(color = last_signal == 1 ? color.blue : last_signal == -1 ? color.red : color.gray)


// supertrend
st_length = input.int(50, title = 'Supertrend Length', group = 'Supertrend Settings')
st_factor = input.float(1.5, title = 'Supertrend Factor', group = 'Supertrend Settings')
[supertrend, direction] = ta.supertrend(st_factor, st_length)
plot(supertrend, title = 'Supertrend Circles', color = direction < 0 ? color.green : color.red, style = plot.style_circles, linewidth = 2)



// alt mas
ma1_length = input.int(20, title = 'MA 1 Length', group = 'MA Settings')
ma2_length = input.int(50, title = 'MA 2 Length', group = 'MA Settings')


plot(ta.sma(close,ma1_length), title = 'MA 1', color = color.blue)
plot(ta.sma(close,ma2_length), title = 'MA 2', color = color.green)



// middle ema
middle_source = input.source(close, title = 'Middle Source', group = 'Middle MA')
middle_ema_type = input.string("SMA", title = 'Middle Type', 
 options = ['SMA', 'EMA', 'HMA', 'RMA'], group = 'Middle MA')
middle_length = input.int(20, title = 'Middle Length', group = 'Middle MA')
middle_smoothing = input.int(3, title = 'Middle Smoothing', group = 'Middle MA')
float middle_value = switch middle_ema_type
    "EMA" => ta.ema(middle_source, middle_length)
    "SMA" => ta.sma(middle_source, middle_length)
    "RMA" => ta.rma(middle_source, middle_length)
    "HMA" => ta.hma(middle_source, middle_length)
    => ta.sma(middle_source, middle_length)
middle_ema_value = ta.ema(middle_value, middle_smoothing)
middle_ema_color = middle_ema_value > middle_ema_value[1] ? color.lime : color.rgb(255, 0, 0)
plot(middle_ema_value, title = 'Middle MA', color= middle_ema_color, linewidth = 3)