// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © atraderstoolbox

// I want to use the following indicators to create a “Buy and Sell Alerts” indicator.

// - Vumanchu Cipher B
// - RSI

// Buy Signal

// 1. Price should form lower lows, while the green momentum dots on Cipher B are printing higher lows on the same candles. Examples below
// 2. Money Flow should be in an uptrend over the past vs the past 10 candles
// 3. RSI should be under 50 when the 2nd green dot is printed.
// 4. Only consider green dots from under the zero line
// 5. The first large blue wave must be under -70


// Sell Signal

// 1. Price should form higher highs, while the red momentum dots on Cipher B are printing lower highs on the same candles. Examples below
// 2. Money Flow should be in an downtrend over the past vs the past 10 candles
// 3. RSI should be over 50 when the 2nd red dot is printed.
// 4. Only consider red dots from over the zero line
// 5. The first large blue wave must be under -70


//@version=5
indicator("for_directoriestoda", overlay = true)
plot(close)
