// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © atraderstoolbox

//@version=5
indicator("for_manganet_1min", overlay = true, max_lines_count = 500)

line1_amount = input.int(2, minval = 1, title = 'Line One', group = 'Settings', inline ='1')
line1_color = input.color(color.new(color.yellow,0), title = '', group = 'Settings', inline ='1')
line1_style = input.string('Solid', title = '', options = ['Solid', 'Dotted', 'Dashed'], group = 'Settings', inline ='1')
line1_width = input.int(1, title = '', minval = 1, maxval = 5, group = 'Settings', inline ='1')

line2_amount = input.int(6, minval = 1, title = 'Line Two', group = 'Settings', inline ='2')
line2_color = input.color(color.new(color.green,0), title = '', group = 'Settings', inline ='2')
line2_style = input.string('Solid', title = '', options = ['Solid', 'Dotted', 'Dashed'], group = 'Settings', inline ='2')
line2_width = input.int(1, title = '', minval = 1, maxval = 5, group = 'Settings', inline ='2')

closeline_color = input.color(color.new(color.gray,0), title = 'Line Close', group = 'Settings', inline ='3')
closeline_style = input.string('Dashed', title = '', options = ['Solid', 'Dotted', 'Dashed'], group = 'Settings', inline ='3')
closeline_width = input.int(1, title = '', minval = 1, maxval = 5, group = 'Settings', inline ='3')

keep_old_lines = input.bool(true, title = 'Keep Old Lines', group = 'Settings', inline ='4')
color_to_switch = input.color(color.blue, title = 'Switching Color', group = 'Settings', inline ='5')


var float last_confirmed_bar_index = na
last_confirmed_bar_index := barstate.islastconfirmedhistory ? bar_index : last_confirmed_bar_index[1]
plotchar(bar_index == last_confirmed_bar_index ? true : false, title = 'Start Calculating', char = 'x', color = color.white)


var line_close = array.new_line(100,na)
var line1_upper = array.new_line(100,na)
var line1_lower = array.new_line(100,na)
var line2_upper = array.new_line(100,na)
var line2_lower = array.new_line(100,na)

varip float line1_upper_value = 0 
varip float line1_lower_value = 0
varip float line2_upper_value = 0 
varip float line2_lower_value = 0

varip float min_high = na
varip float min_low = na
varip float min_close = na
var bool min_confirm = na

// request minute data
min_highs =  request.security_lower_tf(syminfo.tickerid, '1', high)
min_lows =  request.security_lower_tf(syminfo.tickerid, '1', low)
min_closes =  request.security_lower_tf(syminfo.tickerid, '1', close)
min_confirms =  request.security_lower_tf(syminfo.tickerid, '1', barstate.isrealtime)

min_high := array.last(min_highs)
min_low := array.last(min_lows)
min_close := array.last(min_closes)
min_confirm := array.last(min_confirms)


// function to draw lines
f_drawlines(line_close, line1_upper, line1_lower, line2_upper, line2_lower, anchor) =>

    array.unshift(line_close, line.new(x1 = bar_index, y1 = anchor, x2 = bar_index+1, y2 = anchor, xloc = xloc.bar_index,
         extend = extend.right, color = closeline_color, width = closeline_width,
         style = (closeline_style == 'Solid' ? line.style_solid : closeline_style == 'Dashed' ? line.style_dashed : closeline_style == 'Dotted' ? line.style_dotted : line.style_solid)))

    array.unshift(line1_upper, line.new(x1 = bar_index, y1 = anchor + syminfo.mintick*line1_amount, x2 = bar_index+1, y2 = anchor + syminfo.mintick*line1_amount, xloc = xloc.bar_index,
         extend = extend.right, color = line1_color, width = line1_width,
         style = (line1_style == 'Solid' ? line.style_solid : line1_style == 'Dashed' ? line.style_dashed : line1_style == 'Dotted' ? line.style_dotted : line.style_solid)))

    array.unshift(line1_lower, line.new(x1 = bar_index, y1 = anchor - syminfo.mintick*line1_amount, x2 = bar_index+1, y2 = anchor - syminfo.mintick*line1_amount, xloc = xloc.bar_index,
         extend = extend.right, color = line1_color, width = line1_width,
         style = (line1_style == 'Solid' ? line.style_solid : line1_style == 'Dashed' ? line.style_dashed : line1_style == 'Dotted' ? line.style_dotted : line.style_solid)))

    array.unshift(line2_upper, line.new(x1 = bar_index, y1 = anchor + syminfo.mintick*line2_amount, x2 = bar_index+1, y2 = anchor + syminfo.mintick*line2_amount, xloc = xloc.bar_index,
         extend = extend.right, color = line2_color, width = line2_width,
         style = (line2_style == 'Solid' ? line.style_solid : line2_style == 'Dashed' ? line.style_dashed : line2_style == 'Dotted' ? line.style_dotted : line.style_solid)))

    array.unshift(line2_lower, line.new(x1 = bar_index, y1 = anchor - syminfo.mintick*line2_amount, x2 = bar_index+1, y2 = anchor - syminfo.mintick*line2_amount, xloc = xloc.bar_index,
         extend = extend.right, color = line2_color, width = line2_width,
         style = (line2_style == 'Solid' ? line.style_solid : line2_style == 'Dashed' ? line.style_dashed : line2_style == 'Dotted' ? line.style_dotted : line.style_solid)))


 // first bar_index line
if bar_index == last_confirmed_bar_index
    f_drawlines(line_close, line1_upper, line1_lower, line2_upper, line2_lower, array.last(min_closes)) 

// past confirmed bar_index
if bar_index > last_confirmed_bar_index

    // get line values
    line1_upper_value := line.get_y1(array.first(line1_upper))
    line1_lower_value := line.get_y1(array.first(line1_lower))

    line2_upper_value := line.get_y1(array.first(line2_upper))
    line2_lower_value := line.get_y1(array.first(line2_lower))

    // // extend x2 to current bar's bar_index
    line.set_x2(array.first(line_close), bar_index)
    line.set_x2(array.first(line1_upper), bar_index)
    line.set_x2(array.first(line1_lower), bar_index)
    line.set_x2(array.first(line2_upper), bar_index)
    line.set_x2(array.first(line2_lower), bar_index)

    // replace colors line 1
    if min_high >= line1_upper_value
        line.set_color(array.first(line1_upper), color_to_switch)
    if min_low <= line1_lower_value
        line.set_color(array.first(line1_lower), color_to_switch)

    // replace colors line 2 
    if min_high >= line2_upper_value or min_low <= line2_lower_value
        line.set_color(array.first(line_close), color_to_switch)
        line.set_color(array.first(line1_upper), color_to_switch)
        line.set_color(array.first(line1_lower), color_to_switch)
        line.set_color(array.first(line2_upper), color_to_switch)
        line.set_color(array.first(line2_lower), color_to_switch)

        // make new lines / delete old lines on the bars closing update
        if min_confirm
            if not keep_old_lines
                line.delete(array.first(line_close))
                line.delete(array.first(line1_upper))
                line.delete(array.first(line1_lower))
                line.delete(array.first(line2_upper))
                line.delete(array.first(line2_lower))

            // end extension since lines aren't being deleted
            line.set_extend(array.first(line_close), extend.none)
            line.set_extend(array.first(line1_upper), extend.none)
            line.set_extend(array.first(line1_lower), extend.none)
            line.set_extend(array.first(line2_upper), extend.none)
            line.set_extend(array.first(line2_lower), extend.none)
            
        // draw new lines
        f_drawlines(line_close, line1_upper, line1_lower, line2_upper, line2_lower, min_close)
        

// bgcolor(bar_index > last_confirmed_bar_index ? color.gray : na)
label.new(bar_index, 24150, str.tostring(min_confirm), color = color.white)
label.new(bar_index, min_close, text = str.tostring(min_close), color = color.white)
