//@version=5
indicator('GAIN28', max_lines_count=500, max_bars_back = 5000)

////////////
// INPUTS //

per        = input.int(title = 'Period for signal',     defval = 14, minval = 1, maxval = 200)
drawShift  = input.int(title = 'Forward shift',         defval = 14, minval = 0, maxval = 200)
maPeriod   = input.int(title = 'Moving average period', defval = 34, minval = 0, maxval = 200)
useMA      = input.int(title = '1 = use MA',            defval = 1,  minval = 0, maxval = 1)
useSignal2 = input.int(title = 'Show current close - open shifted forward', defval = 0, minval = 0, maxval = 1)

///////////////
// FUNCTIONS //

truncate(number, decimals) =>
    factor = math.pow(10, decimals)
    int(number * factor) / factor

iMAOnArray(array, period, ma_shift, shift) =>
    buf = array.new_float(0)
    total = array.size(array)
    return_1 = 0
    if total > period and shift <= total - period - ma_shift
        buf := array.slice(array, shift, period + shift)
        truncate(array.sum(buf) / period, 3)

pine_sum(bars) =>
    sum = 0.0
    lim = 0
    if bars > per
        lim := bars - per
        lim
    else
        lim := 0
        lim

    for i = bars to lim by 1
        sum += (close[i] - open[i]) / syminfo.mintick
        sum
    sum

//////////////////
// CALCULATIONS //

// Find Bars in week
var bars_array = array.new_int(na)
cur_bars_in_week = int(na) 
new_week = dayofweek(time) == 2 and dayofweek(time[1]) != 2
cur_bars_in_week := new_week ? ta.barssince(new_week)[1] + 1 : nz(cur_bars_in_week[1])

if (new_week and not na(cur_bars_in_week))
    array.push(bars_array, cur_bars_in_week)
    
bars_in_week = array.mode(bars_array)

// 
float imp   = math.sum(close - open, per + 1) / syminfo.mintick
float sum34 = 0
a           = array.new_float(0)
newShift    = 0

d = 0.0
dt = int(ta.lowest(time - time[1], 10))

if barstate.islast and drawShift > 0
    d := imp
    t   = drawShift > 14? drawShift-14 : 0
    //array.reverse(a)
    for i = 14 to 1 by 1
        
        dt1 = int(na)
        dt2 = int(na) 
        
        if (timeframe.isweekly)
            dt1 := time + 1000 * 60 * 60 * 24 * 7 * (14 - i) * timeframe.multiplier
            dt2 := time + 1000 * 60 * 60 * 24 * 7 * (14 - i + 1) * timeframe.multiplier
        else if (timeframe.isminutes and timeframe.multiplier <= 5)
            dt1 := time + 1000 * 60 * (14 - i) * timeframe.multiplier
            dt2 := time + 1000 * 60 * (14 - i + 1) * timeframe.multiplier
        else if (timeframe.isdaily)
            dt1 := time + (time[bars_in_week - (14 - i) % bars_in_week]     - time[bars_in_week]) + int((14 - i) / bars_in_week)     * 1000 * 60 * 60 * 24 * 7
            dt2 := time + (time[bars_in_week - (14 - i + 1) % bars_in_week] - time[bars_in_week]) + int((14 - i + 1) / bars_in_week) * 1000 * 60 * 60 * 24 * 7
        else
            dt1 := time + (time[bars_in_week - 14 + i]     - time[bars_in_week])
            dt2 := time + (time[bars_in_week - 14 + i - 1] - time[bars_in_week]) 
            
        line.new(dt1, d, dt2, pine_sum(i - 1), xloc = xloc.bar_time, color=color.red)
        d := pine_sum(i - 1)
        t := t+1



if barstate.islast and drawShift > 0
    for i = bar_index - (maPeriod + drawShift) to bar_index by 1
        array.push(a, pine_sum(bar_index - i))

if bar_index > per + maPeriod
    for i = 0 to maPeriod by 1
        for j = i to i + per by 1
            sum34 += (close[j] - open[j]) / syminfo.mintick
            sum34


d2 = 0.0
if barstate.islast and drawShift > 0
    d2 := sum34 / maPeriod
    t2 = drawShift > 14 ? drawShift - 14 : 0
    for i = 1 to 14 by 1
    
        dt1 = int(na)
        dt2 = int(na) 

        if (timeframe.isweekly)
            dt1 := time + 1000 * 60 * 60 * 24 * 7 * (i -1) * timeframe.multiplier
            dt2 := time + 1000 * 60 * 60 * 24 * 7 * (i) * timeframe.multiplier
        else if (timeframe.isminutes and timeframe.multiplier <= 5)
            dt1 := time + 1000 * 60 * (i - 1) * timeframe.multiplier
            dt2 := time + 1000 * 60 * (i) * timeframe.multiplier  
        else if (timeframe.isdaily)
            dt1 := time + (time[bars_in_week - (i - 1) % bars_in_week] - time[bars_in_week]) + int((i - 1) / bars_in_week) * 1000 * 60 * 60 * 24 * 7
            dt2 := time + (time[bars_in_week - (i) % bars_in_week]     - time[bars_in_week]) + int((i) / bars_in_week)     * 1000 * 60 * 60 * 24 * 7
        else
            dt1 := time + (time[bars_in_week - i + 1] - time[bars_in_week])
            dt2 := time + (time[bars_in_week - i]     - time[bars_in_week]) 

        
        line.new(dt1, d2, dt2, iMAOnArray(a, maPeriod, 0, i), xloc=xloc.bar_time, color=color.green)
        d2 := iMAOnArray(a, maPeriod, 0, i)
        t2 += 1
        t2

if drawShift > 14
    newShift := drawShift - 14
    newShift

plot(imp,                                                               style = plot.style_line, color=color.new(color.red, 0),   offset = newShift)
plot(useSignal2 == 1 ? (close - open) / syminfo.mintick : na,           style = plot.style_line, color=color.new(color.blue, 0),  offset = newShift)
plot(useMA == 1 and bar_index > per + maPeriod ? sum34 / maPeriod : na, style = plot.style_line, color=color.new(color.green, 0), offset = newShift)