//@version=5
indicator(title="GM VWAP", shorttitle="VWAP", overlay=true)

var cumVol = 0.
cumVol += nz(volume)
if barstate.islast and cumVol == 0
    runtime.error("No volume is provided by the data vendor.")
    
computeVWAP(src, isNewPeriod, stDevMultiplier, stDevMultiplier2) =>
	var float sumSrcVol = na
	var float sumVol = na
    var float sumSrcSrcVol = na

	sumSrcVol := isNewPeriod ? src * volume : src * volume + sumSrcVol[1]
	sumVol := isNewPeriod ? volume : volume + sumVol[1]
	// sumSrcSrcVol calculates the dividend of the equation that is later used to calculate the standard deviation
	sumSrcSrcVol := isNewPeriod ? volume * math.pow(src, 2) : volume * math.pow(src, 2) + sumSrcSrcVol[1]

	_vwap = sumSrcVol / sumVol
	variance = sumSrcSrcVol / sumVol - math.pow(_vwap, 2)
	variance := variance < 0 ? 0 : variance
	stDev = math.sqrt(variance)

	lowerBand = _vwap - stDev * stDevMultiplier
	upperBand = _vwap + stDev * stDevMultiplier
	
	lowerBand2 = _vwap - stDev * stDevMultiplier2
	upperBand2 = _vwap + stDev * stDevMultiplier2

	[_vwap, lowerBand, upperBand, lowerBand2, upperBand2]

hideonDWM = input(true, title="Hide VWAP on 1hr or Above", group="VWAP Settings")
var anchor = input.string(defval = "Session", title="Anchor Period",
 options=["Session", "Week", "Month", "Quarter", "Year", "Decade", "Century", "Earnings", "Dividends", "Splits"], group="VWAP Settings")
src = input(title = "Source", defval = hlc3, group="VWAP Settings")
offset = input(0, title="Offset", group="VWAP Settings")

showBands = input(true, title="Calculate Bands", group="Standard Deviation Bands Settings")
stdevMult1 = input(2.0, title="Bands Multiplier", group="Standard Deviation Bands Settings")
stdevMult2 = input(3.25, title="Bands Multiplier", group="Standard Deviation Bands Settings")

timeChange(period) =>
	ta.change(time(period))

new_earnings = request.earnings(syminfo.tickerid, earnings.actual, barmerge.gaps_on, barmerge.lookahead_on, ignore_invalid_symbol=true)
new_dividends = request.dividends(syminfo.tickerid, dividends.gross, barmerge.gaps_on, barmerge.lookahead_on, ignore_invalid_symbol=true)
new_split = request.splits(syminfo.tickerid, splits.denominator, barmerge.gaps_on, barmerge.lookahead_on, ignore_invalid_symbol=true)

isNewPeriod = switch anchor
	"Earnings" => not na(new_earnings)
	"Dividends" => not na(new_dividends)
	"Splits" => not na(new_split)
	"Session" => timeChange("D")
	"Week" => timeChange("W")
	"Month" => timeChange("M")
	"Quarter" => timeChange("3M")
	"Year" => timeChange("12M")
	"Decade" => timeChange("12M") and year % 10 == 0
	"Century" => timeChange("12M") and year % 100 == 0
	=> false

isEsdAnchor = anchor == "Earnings" or anchor == "Dividends" or anchor == "Splits"
if na(src[1]) and not isEsdAnchor
	isNewPeriod := true

float vwapValue = na
float std = na
float upperBandValue = na
float lowerBandValue = na
float upperBandValue2 = na
float lowerBandValue2 = na

hide_cond = timeframe.multiplier > 15 or timeframe.isdwm

if not (hideonDWM and hide_cond)
    [_vwap, bottom, top, bottom2, top2] = computeVWAP(src, isNewPeriod, stdevMult1, stdevMult2)
    vwapValue := _vwap
    upperBandValue := showBands ? top : na
    lowerBandValue := showBands ? bottom : na
    upperBandValue2 := showBands ? top2 : na
    lowerBandValue2 := showBands ? bottom2 : na

plot(vwapValue, title="VWAP", color=color.new(#131722,60), offset=offset, display = display.all)

upperBand = plot(upperBandValue, title="Upper Band", color=color.white, offset=offset, display = display.none)
lowerBand = plot(lowerBandValue, title="Lower Band", color=color.white, offset=offset, display = display.none)

upperBand2 = plot(upperBandValue2, title="Upper Band 2", color=color.white, offset=offset, display = display.none)
lowerBand2 = plot(lowerBandValue2, title="Lower Band 2", color=color.white, offset=offset, display = display.none)

fill(upperBand, upperBand2, title="Bands Fill", color= showBands ? color.new(#131722, 85) : na)
fill(lowerBand, lowerBand2, title="Bands Fill", color= showBands ? color.new(#131722, 85) : na)



