// © goodgains
//
// Last update: 23/04/2022
// *************************************************************************************************************************************************************************************************************************************************************************
//@version=5
strategy(title="Ichimoku Cloud with Linear Regression Strategy", overlay=true, precision=2, commission_value=0.075, commission_type=strategy.commission.percent, initial_capital=1000, currency=currency.USD, default_qty_type=strategy.percent_of_equity, default_qty_value=100, slippage=1)

// @keywords: ichimoku-cloud, linear-regression, weighted-strategy, macd, stoch-rsi, rsi, supertrend, ma-cross, ppo, bollinger-bands, hull-moving-average, kijun, ssl-channel, stop-loss, take-profit, top-bottom, monthly-pnl-table, alerts, crossover, vwap

// *************************************************************************************************************************************************************************************************************************************************************************
// COMMENTS
// *************************************************************************************************************************************************************************************************************************************************************************


// *************************************************************************************************************************************************************************************************************************************************************************
// INPUTS
// *************************************************************************************************************************************************************************************************************************************************************************
// * Type trading
allow_longs = input.bool(true, 'Allow Longs', group='Trading type')
allow_shorts = input.bool(true, 'Allow Shorts', group='Trading type')
// * Datastamp
from_day = input.int(1, 'From Day', minval=1, maxval=31, group='DataStamp')
from_month = input.int(1, 'From Month', minval=1, maxval=12, group='DataStamp')
from_year = input.int(2021, 'From Year', minval=1980, maxval=9999, group='DataStamp')
to_day = input.int(1, 'To Day', minval=1, maxval=31, group='DataStamp')
to_month = input.int(1, 'To Month', minval=1, maxval=12, group='DataStamp')
to_year = input.int(9999, 'To Year', minval=2017, maxval=9999, group='DataStamp')
// * Stop loss
stoploss = input.bool(true, 'Stop loss', group='Stop loss')
movestoploss = input.string('TP-2', 'Move stop loss', options=['None', 'Percentage', 'TP-1', 'TP-2', 'TP-3'], group='Stop loss')
movestoploss_entry = input.bool(false, 'Move stop loss to entry', group='Stop loss')
stoploss_setting = input.float(6.0, 'Stop Loss %', minval=0, maxval=100, group='Stop loss')
stoploss_perc = stoploss_setting * 0.01
move_stoploss_factor = input.float(20.0, 'Move stop loss factor %', group='Stop loss') * 0.01 + 1
stop_source = input.source(hl2, 'Stop Source', group='Stop loss')
// * Take profits
take_profits = input.bool(true, 'Take profits', group='Take Profits')
// retrade= input.bool(false, 'Retrade', group='Take Profits')
MAX_TP = input.int(6, 'Max number of TP', minval=1, maxval=6, group='Take Profits')
long_profit_perc_setting = input.float(6.8, 'Long - take profits each x (%)', minval=0.0, maxval=999, step=1, group='Take Profits')
long_profit_perc =  long_profit_perc_setting * 0.01
long_profit_qty = input.float(15, 'Long - take x (%) from open position', minval=0.0, maxval=100, step=1, group='Take Profits')
short_profit_perc_setting = input.float(13, 'Short - take profits each x (%)', minval=0.0, maxval=999, step=1, group='Take Profits')
short_profit_perc =  short_profit_perc_setting * 0.01
short_profit_qty = input.float(10, 'Short - take x (%) from open position', minval=0.0, maxval=100, step=1, group='Take Profits')
// * Delays
delay_macd = input.int(1, 'Candles delay MACD', minval=1, group='Delays')
delay_srsi = input.int(2, 'Candles delay Stoch RSI', minval=1, group='Delays')
delay_rsi = input.int(2, 'Candles delay RSI', minval=1, group='Delays')
delay_super = input.int(1, 'Candles delay Supertrend', minval=1, group='Delays')
delay_cross = input.int(1, 'Candles delay MA cross', minval=1, group='Delays')
delay_exit = input.int(7, 'Candles delay exit', minval=1, group='Delays')
// * Inputs Weigthed strategies
str_0 = input.bool(true, 'Strategy 0: Weighted Strategy', group='Weights')
weight_trigger = input.int(2, 'Weight Signal entry [0, 5]', minval=0, maxval=5, step=1, group='Weights')
weight_str1 = input.int(1, 'Weight Strategy 1 [0, 5]', minval=0, maxval=5, step=1, group='Weights')
weight_str2 = input.int(1, 'Weight Strategy 2 [0, 5]', minval=0, maxval=5, step=1, group='Weights')
weight_str3 = input.int(1, 'Weight Strategy 3 [0, 5]', minval=0, maxval=5, step=1, group='Weights')
weight_str4 = input.int(1, 'Weight Strategy 4 [0, 5]', minval=0, maxval=5, step=1, group='Weights')
weight_str5 = input.int(1, 'Weight Strategy 5 [0, 5]', minval=0, maxval=5, step=1, group='Weights')
weight_str6 = input.int(1, 'Weight Strategy 6 [0, 5]', minval=0, maxval=5, step=1, group='Weights')
weight_str7 = input.int(1, 'Weight Strategy 7 [0, 5]', minval=0, maxval=5, step=1, group='Weights')
// * Inputs strategy 1: MACD
str_1 = input.bool(true, 'Strategy 1: MACD', group='Strategy 1: MACD')
MA1_period_1 = input.int(16, 'MA 1', minval=1, maxval=9999, step=1, group='Strategy 1: MACD')
MA1_type_1 = input.string('EMA', 'MA1 Type', options=['RMA', 'SMA', 'EMA', 'WMA', 'HMA', 'DEMA', 'TEMA', 'VWMA'], group='Strategy 1: MACD')
MA1_source_1 = input.source(hl2, 'MA1 Source', group='Strategy 1: MACD')
MA2_period_1 = input.int(36, 'MA 2', minval=1, maxval=9999, step=1, group='Strategy 1: MACD')
MA2_type_1 = input.string('EMA', 'MA2 Type', options=['RMA', 'SMA', 'EMA', 'WMA', 'HMA', 'DEMA', 'TEMA', 'VWMA'], group='Strategy 1: MACD')
MA2_source_1 = input.source(high, 'MA2 Source', group='Strategy 1: MACD')
// * Inputs strategy 2: Stoch RSI oversold/overbought
str_2 = input.bool(true, 'Strategy 2: Stoch RSI', group='Strategy 2: Stoch RSI')
long_RSI = input.float(70, 'Exit SRSI Long (%)', minval=0.0, step=1, group='Strategy 2: Stoch RSI')
short_RSI = input.float(27, 'Exit SRSI Short (%)', minval=0.0, step=1, group='Strategy 2: Stoch RSI')
length_RSI = input.int(14, 'RSI Length', group='Strategy 2: Stoch RSI')
length_stoch = input.int(14, 'RSI Stochastic', group='Strategy 2: Stoch RSI')
smoothK = input.int(3, 'Smooth k', group='Strategy 2: Stoch RSI')
// * Inputs strategy 3: RSI oversold/overbought
str_3 = input.bool(true, 'Strategy 3: RSI', group='Strategy 3: RSI')
long_RSI2 = input.float(77, 'Exit RSI Long (%)', minval=0.0, step=1, group='Strategy 3: RSI')
short_RSI2 = input.float(30, 'Exit RSI Short (%)', minval=0.0, step=1, group='Strategy 3: RSI')
// * Inputs strategy 4: Supertrend
str_4 = input.bool(true, 'Strategy 4: Supertrend', group='Strategy 4: Supertrend')
periods_4 = input.int(2, 'ATR Period', group='Strategy 4: Supertrend')
source_4 = input.source(hl2, 'Source', group='Strategy 4: Supertrend')
multiplier = input.float(2.4, 'ATR Multiplier', step=0.1, group='Strategy 4: Supertrend')
change_ATR = input.bool(true, 'Change ATR Calculation Method ?', group='Strategy 4: Supertrend')
// * Inputs strategy 5: MA CROSS
str_5 = input.bool(true, 'Strategy 5: MA CROSS', group='Strategy 5: MA CROSS')
MA1_period_5 = input.int(46, 'MA 1', minval=1, maxval=9999, step=1, group='Strategy 5: MA CROSS')
MA1_type_5 = input.string('EMA', 'MA1 Type', options=['RMA', 'SMA', 'EMA', 'WMA', 'HMA', 'DEMA', 'TEMA', 'VWMA'], group='Strategy 5: MA CROSS')
MA1_source_5 = input.source(close, 'MA1 Source', group='Strategy 5: MA CROSS')
MA2_period_5 = input.int(82, 'MA 2', minval=1, maxval=9999, step=1, group='Strategy 5: MA CROSS')
MA2_type_5 = input.string('EMA', 'MA2 Type', options=['RMA', 'SMA', 'EMA', 'WMA', 'HMA', 'DEMA', 'TEMA', 'VWMA'], group='Strategy 5: MA CROSS')
MA2_source_5 = input.source(close, 'MA2 Source', group='Strategy 5: MA CROSS')
// * Inputs strategy 6: PPO
str_6 = input.bool(true, 'Strategy 6: PPO', group="Strategy 6: PPO")
ppo_study_old = input.bool(true, title="Use Previous Study without overbought-sold", group="Strategy 6: PPO")
ppo_fastLength = input.int(55, minval=1, title="PPO Fast",  group="Strategy 6: PPO")
ppo_slowLength = input.int(26, minval=1, title="PPO Slow", group="Strategy 6: PPO")
ppo_sl = input.int(4, minval=1, title="PPO Signal", group="Strategy 6: PPO")
ppo_smoother = input.int(5, minval=1, title="PPO Smooth", group="Strategy 6: PPO")
ppo_offset = input.float(0.25, title="ALMA offset", group="Strategy 6: PPO")
ppo_period = input.int(defval=50, title="period", group="Strategy 6: PPO")
//BB Settings
ppo_base_ma = input.string("hullma", title = "base ma", options = ["sma", "ema", "wma", "vwma", "swma", "double ema", "triple ema","hullma", "tema"], group="Strategy 6: PPO", inline = "ma")
ppo_length = input.int(55, minval=1, title="Length")
ppo_lengthbol = input.int(21, minval=1)
ppo_src = input.source(close, title = "Sourcebollinger", group="Strategy 6: PPO", inline = "ma")
ppo_mult = input.float(2.0, title = "band multiplier", minval=0.001, maxval=50, group="Strategy 6: PPO", inline = "BB")
///MACD Settings
ppo_fastMA_macdrsi = input.int(title="Fast moving average", defval = 12, minval = 7, group="Strategy 6: PPO") //7 16
ppo_slowMA_macdrsi = input.int(title="Slow moving average", defval = 26, minval = 7, group="Strategy 6: PPO") //24 26
ppo_signalLength_macdrsi = input.int(9, minval=1, group="Strategy 6: PPO") //9 6
//RSI settings
ppo_RSIOverSold_macdrsi = input.int(55 ,minval=1, group="Strategy 6: PPO") //26
ppo_RSIOverBought_macdrsi = input.int(52 ,minval=1, group="Strategy 6: PPO") //77
ppo_src_macdrsi = input.source(close, title='MACDRSI Source', group="Strategy 6: PPO")
ppo_len_macdrsi = input.int(14, minval=1, title="MACDRSI Length", group="Strategy 6: PPO")
// Triple EMA Settings
ppo_incompletecandles_macdrsi=input(true, title="Include current unclosed current candle", group="Strategy 6: PPO")
//type=input(defval="SMA", options=["SMA"],title="MA Type")
ppo_type_macdrsi="EMA"
ppo_forecasttype_macdrsi=input.string(defval="flat", options=["flat", "linreg"], title="MA Forecast Type (flat assumes prices stay the same / linreg does n period LR forecast)", group="Strategy 6: PPO")
ppo_linreglen_macdrsi=input.int(5,title="# of candles to use in linear regression", group="Strategy 6: PPO")
ppo_showshort_macdrsi=input(true, title="Plot Short EMA", group="Strategy 6: PPO")
ppo_len_tema_macdrsi=input.int(7, title="Short EMA Len", group="Strategy 6: PPO")
// * Inputs strategy 7: PPO
str_7 = input.bool(true, 'Strategy 7: Fury', group="Strategy 7: Fury")

fury_show_SSL1 =true
//ATR
fury_atrlen = input(14, 'ATR Period', group="Strategy 7: Fury")
fury_mult = input.float(1, 'ATR Multi', step=0.1, group="Strategy 7: Fury")
fury_smoothing = input.string(title='ATR Smoothing', defval='WMA', options=['RMA', 'SMA', 'EMA', 'WMA'], group="Strategy 7: Fury")
////BASELINE / SSL1 / SSL2 / EXIT MOVING AVERAGE VALUES
fury_maType = input.string(title='SSL1 / Baseline Type', defval='HMA', options=['SMA', 'EMA', 'DEMA', 'TEMA', 'LSMA', 'WMA', 'MF', 'VAMA', 'TMA', 'HMA', 'JMA', 'Kijun v2', 'EDSMA', 'McGinley'], group="Strategy 7: Fury")
fury_len = input(title='SSL1 / Baseline Length', defval=60, group="Strategy 7: Fury")

fury_kidiv = input.int(defval=1, maxval=4, title='Kijun MOD Divider', group="Strategy 7: Fury")

fury_jurik_phase = input(title='* Jurik (JMA) Only - Phase', defval=3, group="Strategy 7: Fury")
fury_jurik_power = input(title='* Jurik (JMA) Only - Power', defval=1, group="Strategy 7: Fury")
fury_volatility_lookback = input(10, title='* Volatility Adjusted (VAMA) Only - Volatility lookback length', group="Strategy 7: Fury")
//MF
fury_beta = input.float(0.8, minval=0, maxval=1, step=0.1, title='Modular Filter, General Filter Only - Beta', group="Strategy 7: Fury")
fury_feedback = input(false, title='Modular Filter Only - Feedback', group="Strategy 7: Fury")
fury_z = input.float(0.5, title='Modular Filter Only - Feedback Weighting', step=0.1, minval=0, maxval=1, group="Strategy 7: Fury")
//EDSMA
fury_ssfLength = input.int(title='EDSMA - Super Smoother Filter Length', minval=1, defval=20, group="Strategy 7: Fury")
fury_ssfPoles = input.int(title='EDSMA - Super Smoother Filter Poles', defval=2, options=[2, 3], group="Strategy 7: Fury")

fury_stsource=input.string('hl2',"Super Trend Source",["hl2","SSL1","hl2c/4","hc/2"], group="Strategy 7: Fury")
fury_Periods = input(title='Super Trend ATR Period', defval=10, group="Strategy 7: Fury")
fury_Multiplier = input.float(title='Super Trend ATR Multiplier', step=0.1, defval=3.0, group="Strategy 7: Fury")
fury_changeATR = input(title='Super Trend Change ATR Calculation Method ?', defval=true, group="Strategy 7: Fury")


// * Inputs Potential TOP/BOTTOM
str_8 = input.bool(false, 'Close order at potential Top/Bottom', group='Potential TOP/BOTTOM')
top_qty = input.float(30, 'Top - take x (%) from the remaining position', minval=0.0, maxval=100, step=1, group='Potential TOP/BOTTOM')
bottom_qty = input.float(30, 'Bottom - take x (%) from the remaining position', minval=0.0, maxval=100, step=1, group='Potential TOP/BOTTOM')
source_6_top = input.source(close, 'TP-TOP at previous?', group='Potential TOP/BOTTOM')
source_6_bottom = input.source(close, 'TP-BOTTOM at previous?', group='Potential TOP/BOTTOM')
long_trail_perc = input.float(150, 'Trail volume Long (%)', minval=0.0, step=1, group='Potential TOP/BOTTOM') * 0.01
short_trail_perc = input.float(150, 'Trail volume Short (%)', minval=0.0, step=1, group='Potential TOP/BOTTOM') * 0.01
// * Flags
FLAG_SIGNALS = input.bool(true, 'Show Buy/Sell Signals ?', group='Miscellaneous')
FLAG_SHADOWS = input.bool(true, 'Show shadows satisfied strategies ?', group='Miscellaneous')
// * Alarms
alarm_label_long = input.string('Buy', 'Label open long', group='Basic alarm system')
alarm_label_short = input.string('Sell', 'Label open short', group='Basic alarm system')
alarm_label_close_long = input.string('Close long', 'Label close long', group='Basic alarm system')
alarm_label_close_short = input.string('Close short', 'Label close short', group='Basic alarm system')
alarm_label_TP_long = input.string('TP long', 'Label Take Profit long', group='Basic alarm system')
alarm_label_TP_short = input.string('TP short', 'Label Take Profit short', group='Basic alarm system')
alarm_label_SL = input.string('SL', 'Label Stop-Loss', group='Basic alarm system')

isrealPrice=input(false,"Enable Real Price Filter", group='Real Price')
so = input(true, 'Show Open Price', group='Real Price')
// sh = input(false, 'Show High Price', group='Real Price')
// sl = input(false, 'Show Low Price', group='Real Price')
// sc = input(false, 'Show Close Price', group='Real Price')
max_dis_pct=input(0.5,"Max Distance %", group='Real Price')

//Real Price{=============================================================================================================

security_1 = request.security(ticker.new(syminfo.prefix, syminfo.ticker), timeframe.period, open)
op = so ? security_1 : na
// security_2 = request.security(ticker.new(syminfo.prefix, syminfo.ticker), timeframe.period, high)
// hi = sh ? security_2 : na
// security_3 = request.security(ticker.new(syminfo.prefix, syminfo.ticker), timeframe.period, low)
// lo = sl ? security_3 : na
// security_4 = request.security(ticker.new(syminfo.prefix, syminfo.ticker), timeframe.period, close)
// cl = sc ? security_4 : na

plot(op, linewidth=1)
// plot(hi, linewidth=1)
// plot(lo, linewidth=1)
// plot(cl, linewidth=1)

percentCalulation(price1,price2)=>
    math.round(math.abs(((price2-price1)/price1)*100),2)

realtime_cond = isrealPrice ? (percentCalulation(open,op) <= max_dis_pct) : true
// bgcolor(realtime_cond? color.new(color.green,50):na)
//Real Price}=============================================================================================================

// *************************************************************************************************************************************************************************************************************************************************************************
// ABBREVIATIONS
// *************************************************************************************************************************************************************************************************************************************************************************
// TP: Take profits
// SL: Stop-Loss
// *************************************************************************************************************************************************************************************************************************************************************************
// GLOBAL VARIABLES
// *************************************************************************************************************************************************************************************************************************************************************************
start = timestamp(from_year, from_month, from_day, 00, 00) // backtest start window
end = timestamp(to_year, to_month, to_day, 23, 59)// backtest finish window
var FLAG_FIRST = false
var price_stop_long = 0.
var price_stop_short = 0.
var profit_qty = 0. // Quantity to close per TP from open position
var profit_perc = 0. // Percentage to take profits since open position or last TP
var nextTP = 0. // Next target to take profits
var since_entry = 0 // Number of bars since open last postion
var since_close = 0 // Number of bars since close or TP/STOP last position

// * Compute profit quantity and profit percentage
if strategy.position_size > 0
    profit_qty := long_profit_qty
    profit_perc := long_profit_perc
else if strategy.position_size < 0
    profit_qty := short_profit_qty
    profit_perc := short_profit_perc
else
    nextTP := 0. // Next Take Profit target (out of market)
// *************************************************************************************************************************************************************************************************************************************************************************
// FUNCTIONS
// *************************************************************************************************************************************************************************************************************************************************************************
// * MA type
// *************************************************************************************************************************************************************************************************************************************************************************
ma(MAType, MASource, MAPeriod) =>
    if MAType == 'SMA'
        ta.sma(MASource, MAPeriod)
    else if MAType == 'EMA'
        ta.ema(MASource, MAPeriod)
    else if MAType == 'WMA'
        ta.wma(MASource, MAPeriod)
    else if MAType == 'RMA'
        ta.rma(MASource, MAPeriod)
    else if MAType == 'HMA'
        ta.wma(2 * ta.wma(MASource, MAPeriod / 2) - ta.wma(MASource, MAPeriod), math.round(math.sqrt(MAPeriod)))
    else if MAType == 'DEMA'
        e = ta.ema(MASource, MAPeriod)
        2 * e - ta.ema(e, MAPeriod)
    else if MAType == 'TEMA'
        e = ta.ema(MASource, MAPeriod)
        3 * (e - ta.ema(e, MAPeriod)) + ta.ema(ta.ema(e, MAPeriod), MAPeriod)
    else if MAType == 'VWMA'
        ta.vwma(MASource, MAPeriod)
// *************************************************************************************************************************************************************************************************************************************************************************
// * Number strategies
// *************************************************************************************************************************************************************************************************************************************************************************
n_strategies() =>
    var result = 0.
    if str_1
        result := 1.
    if str_2
        result += 1.
    if str_3
        result += 1.
    if str_4
        result += 1.
    if str_5
        result += 1.
    if str_6
        result += 1.
// *************************************************************************************************************************************************************************************************************************************************************************
// * Price take profit
// *************************************************************************************************************************************************************************************************************************************************************************
price_takeProfit(percentage, N) =>
    if strategy.position_size > 0
        strategy.position_avg_price * (1 + N * percentage)
    else
        strategy.position_avg_price * (1 - N * percentage)
// *************************************************************************************************************************************************************************************************************************************************************************
// * Weigthed values
// *************************************************************************************************************************************************************************************************************************************************************************
weight_values(signal) =>
    if signal
        weight = 1.0
    else
        weight = 0.
// *************************************************************************************************************************************************************************************************************************************************************************
// * Weigthed total
// *************************************************************************************************************************************************************************************************************************************************************************
weight_total(signal1, signal2, signal3, signal4, signal5, signal16, signal17) =>
    weight_str1 * weight_values(signal1) + weight_str2 * weight_values(signal2) + weight_str3 * weight_values(signal3) + weight_str4 * weight_values(signal4) + weight_str5 * weight_values(signal5) + weight_str6 * weight_values(signal16) + weight_str7 * weight_values(signal17)
// *************************************************************************************************************************************************************************************************************************************************************************
// * Set alert TP message
// *************************************************************************************************************************************************************************************************************************************************************************
set_alarm_label_TP() =>
    if strategy.position_size > 0
        alarm_label_TP_long
    else if strategy.position_size < 0
        alarm_label_TP_short
// *************************************************************************************************************************************************************************************************************************************************************************
// * Color
// *************************************************************************************************************************************************************************************************************************************************************************
colors(type, value=0) =>
    switch str.lower(type)
        'buy'=> color.new(color.aqua, value)
        'sell' => color.new(color.gray, value)
        'TP' => color.new(color.aqua, value)
        'SL' => color.new(color.gray, value)
        'signal' => color.new(color.orange, value)
        'profit' => color.new(color.teal, value)
        'loss' => color.new(color.red, value)
        'info' => color.new(color.white, value)
        'highlights' => color.new(color.orange, value)
// *************************************************************************************************************************************************************************************************************************************************************************
// * Bar since last entry
// *************************************************************************************************************************************************************************************************************************************************************************
bars_since_entry() =>
    bar_index - strategy.opentrades.entry_bar_index(0)
// *************************************************************************************************************************************************************************************************************************************************************************
// * Bar since close or TP/STOP
// *************************************************************************************************************************************************************************************************************************************************************************
bars_since_close() =>
    ta.barssince(ta.change(strategy.closedtrades))
// *************************************************************************************************************************************************************************************************************************************************************************
// ADDITIONAL GLOBAL VARIABLES
// *************************************************************************************************************************************************************************************************************************************************************************
// * Compute time since last entry and last close/TP position
since_entry := bars_since_entry()
since_close := bars_since_close()
if strategy.opentrades == 0
    since_entry := delay_exit
if strategy.closedtrades == 0
    since_close := delay_exit
// *************************************************************************************************************************************************************************************************************************************************************************
// STRATEGIES
// *************************************************************************************************************************************************************************************************************************************************************************
// * STRATEGY 1: MACD
// *************************************************************************************************************************************************************************************************************************************************************************
MA1 = ma(MA1_type_1, MA1_source_1, MA1_period_1)
MA2 = ma(MA2_type_1, MA2_source_1, MA2_period_1)

MACD = MA1 - MA2
signal = ma('SMA', MACD, 9)
trend= MACD - signal

long = MACD > signal
short = MACD < signal
proportion = math.abs(MACD / signal)

// * Conditions
long_signal1 = long and long[delay_macd - 1] and not long[delay_macd]
short_signal1 = short and short[delay_macd - 1] and not short[delay_macd]
close_long1 = short and not long[delay_macd]
close_short1 = long and not short[delay_macd]
// *************************************************************************************************************************************************************************************************************************************************************************
// * STRATEGY 2: STOCH RSI
// *************************************************************************************************************************************************************************************************************************************************************************
rsi = ta.rsi(close, length_RSI)
srsi = ta.stoch(rsi, rsi, rsi, length_stoch)
k = ma('SMA', srsi, smoothK)
isRsiOB = k >= long_RSI
isRsiOS = k <= short_RSI

// * Conditions
long_signal2 = isRsiOS[delay_srsi] and not isRsiOB and since_entry >= delay_exit and since_close >= delay_exit
short_signal2 = isRsiOB[delay_srsi] and not isRsiOS and since_entry >= delay_exit and since_close >= delay_exit
close_long2 = short_signal2
close_short2 = long_signal2
// *************************************************************************************************************************************************************************************************************************************************************************
// * STRATEGY 3: RSI
// *************************************************************************************************************************************************************************************************************************************************************************
isRsiOB2 = rsi >= long_RSI2
isRsiOS2 = rsi <= short_RSI2

// * Conditions
long_signal3 = isRsiOS2[delay_rsi] and not isRsiOB2 and since_entry >= delay_exit and since_close >= delay_exit
short_signal3 = isRsiOB2[delay_rsi] and not isRsiOS2 and since_entry >= delay_exit and since_close >= delay_exit
close_long3 = short_signal3
close_short3 = long_signal3
// *************************************************************************************************************************************************************************************************************************************************************************
// * STRATEGY 4: SUPERTREND
// *************************************************************************************************************************************************************************************************************************************************************************
atr2 = ma('SMA', ta.tr, periods_4)
atr = change_ATR ? ta.atr(periods_4) : atr2
up = source_4 - multiplier * atr
up1 = nz(up[1], up)
up := close[1] > up1 ? math.max(up, up1) : up

dn = source_4 + multiplier * atr
dn1 = nz(dn[1], dn)
dn := close[1] < dn1 ? math.min(dn, dn1) : dn

trend := 1
trend := nz(trend[1], trend)
trend := trend == -1 and close > dn1 ? 1 : trend == 1 and close < up1 ? -1 : trend

// * Conditions
long4 = trend == 1
short4 = trend == -1
long_signal4 = trend == 1 and trend[delay_super - 1] == 1 and trend[delay_super] == -1
short_signal4 = trend == -1 and trend[delay_super - 1] == -1 and trend[delay_super] == 1
changeCond = trend != trend[1]
close_long4 = short_signal4
close_short4 = short_signal4
// *************************************************************************************************************************************************************************************************************************************************************************
// * STRATEGY 5: MA CROSS
// *************************************************************************************************************************************************************************************************************************************************************************
MA12 = ma(MA1_type_5, MA1_source_5, MA1_period_5)
MA22 = ma(MA2_type_5, MA2_source_5, MA2_period_5)

long5 = MA12 > MA22
short5 = MA12 < MA22

// * Conditions
long_signal5 = long5 and long5[delay_cross - 1] and not long5[delay_cross]
short_signal5 = short5 and short5[delay_cross - 1] and not short5[delay_cross]
close_long5 = short5 and not long5[delay_cross]
close_short5 = long5 and not short5[delay_cross]
// *************************************************************************************************************************************************************************************************************************************************************************
// * STRATEGY 7: PPO
// *************************************************************************************************************************************************************************************************************************************************************************
ppo_rsiValue_macdrsi = ta.rsi(ppo_src_macdrsi, ppo_len_macdrsi)
ppo_up_macdrsi = ta.rma(math.max(ta.change(ppo_src_macdrsi), 0), ppo_len_macdrsi)
ppo_down_macdrsi = ta.rma(-math.min(ta.change(ppo_src_macdrsi), 0), ppo_len_macdrsi)
ppo_rsi_macdrsi = ppo_down_macdrsi == 0 ? 100 : ppo_up_macdrsi == 0 ? 0 : 100 - (100 / (1 + ppo_up_macdrsi / ppo_down_macdrsi))
ppo_wasOversold_macdrsi = ppo_rsi_macdrsi[0] <= ppo_RSIOverSold_macdrsi or ppo_rsi_macdrsi[1] <= ppo_RSIOverSold_macdrsi or ppo_rsi_macdrsi[2] <= ppo_RSIOverSold_macdrsi or ppo_rsi_macdrsi[3] <= ppo_RSIOverSold_macdrsi or ppo_rsi_macdrsi[4] <= ppo_RSIOverSold_macdrsi or ppo_rsi_macdrsi[5] <= ppo_RSIOverSold_macdrsi
ppo_wasOverbought_macdrsi = ppo_rsi_macdrsi[0] >= ppo_RSIOverBought_macdrsi or ppo_rsi_macdrsi[1] >= ppo_RSIOverBought_macdrsi or ppo_rsi_macdrsi[2] >= ppo_RSIOverBought_macdrsi or ppo_rsi_macdrsi[3] >= ppo_RSIOverBought_macdrsi or ppo_rsi_macdrsi[4] >= ppo_RSIOverBought_macdrsi or ppo_rsi_macdrsi[5] >= ppo_RSIOverBought_macdrsi

hullma(_src, _len) =>
    hullma = ta.wma(2 * ta.wma(_src, _len / 2) - ta.wma(_src, _len), math.round(math.sqrt(_len)))
    hullma

tema(_src, _len) =>
    ema1 = ta.ema(_src, _len)
    ema2 = ta.ema(ema1, _len)
    ema3 = ta.ema(ema2, _len)
    tema = 3 * (ema1 - ema2) + ema3
    tema

matype(_type,_src,_len)=>
    _len==0 ? _src :
     _type=="EMA" ? ta.ema(_src,_len):
     na

HMA(l) =>
    n2ma = 2 * ta.wma(close, math.round(l / 2))
    nma = ta.wma(close, l)
    diff = n2ma - nma
    sqn = math.round(math.sqrt(l))
    n2ma1 = 2 * ta.wma(close[1], math.round(l / 2))
    nma1 = ta.wma(close[1], l)
    diff1 = n2ma1 - nma1
    sqn1 = math.round(math.sqrt(l))
    h1 = ta.wma(diff, sqn)
    h2 = ta.wma(diff1, sqn)
    [h1, h2]


ppo_source= close
ppo_basis2 = ta.sma(ppo_source, ppo_lengthbol)
ppo_t = time("W")

ppo_src_low = (high + low + 2 * close) / 4
ppo_src_2_high = close > open ? (high + close) / 2 : (low + close) / 2
ppo_vwapval = ta.vwap(close)

ppo_start1 = na(ppo_t[1]) or ppo_t > ppo_t[1]

ppo_sumSrc = ppo_source * volume
ppo_sumVol = volume
ppo_sumSrc := ppo_start1 ? ppo_sumSrc : ppo_sumSrc + ppo_sumSrc[1]
ppo_sumVol := ppo_start1 ? ppo_sumVol : ppo_sumVol + ppo_sumVol[1]

ppo_fastMA = ta.alma(ppo_src_low , ppo_fastLength, ppo_offset, ppo_smoother)
ppo_slowMA = ta.alma(ppo_src_2_high, ppo_slowLength, ppo_offset, ppo_smoother)
ppo_macd = ppo_fastMA - ppo_slowMA
ppo_macd2 = ppo_macd / ppo_slowMA * 100
ppo_d = ta.hma(ppo_macd2, ppo_smoother)  // smoothing PPO

// tendencia

[ppo_h1,ppo_h2] = HMA(ppo_period)

ppo_sma_1       =    ta.sma(  ppo_src, ppo_length)
ppo_ema_1       =    ta.ema(  ppo_src, ppo_length)
ppo_wma_1       =    ta.wma(  ppo_src, ppo_length)
ppo_vwma_1      =    ta.vwma(  ppo_src, ppo_length)
ppo_swma_1      =    ta.swma(  ppo_src)
ppo_ema_2       =    ta.ema(ppo_ema_1, ppo_length)
ppo_ema_3       =    ta.ema(ppo_ema_2, ppo_length)
ppo_hullma__1   =    hullma(  ppo_src, ppo_length)
ppo_tema__1     =    tema(  ppo_src, ppo_length)
ppo_sma_2       =    ta.sma(  ppo_src, ppo_length)

ppo_basis =
 ppo_base_ma == "sma"        ? ppo_sma_1     :
 ppo_base_ma == "ema"        ? ppo_ema_1     :
 ppo_base_ma == "wma"        ? ppo_wma_1     :
 ppo_base_ma == "vwma"       ? ppo_vwma_1    :
 ppo_base_ma == "swma"       ? ppo_swma_1    :
 ppo_base_ma == "double ema" ? ppo_ema_2     :
 ppo_base_ma == "triple ema" ? ppo_ema_3     :
 ppo_base_ma == "hullma"     ? ppo_hullma__1 :
 ppo_base_ma == "tema"       ? ppo_tema__1   : ppo_sma_2

// BBand calculations
ppo_dev =  ppo_mult * ta.stdev( ppo_src,  ppo_length)
ppo_upperBB = ppo_basis + ppo_dev
ppo_lowerBB = ppo_basis - ppo_dev

// Trend calculations
var bool ppo_down   = bool(na)
var bool ppo_up     = bool(na)
ppo_stop_line       = float(na)

ppo_crossover_1     = ta.crossover( ppo_src, ppo_upperBB)
ppo_crossunder_1    = ta.crossunder(ppo_src, ppo_lowerBB)

if ppo_crossover_1
    ppo_up      := true
    ppo_down    := false

if ppo_crossunder_1
    ppo_up      := false
    ppo_down    := true


ppo_change_up       = ppo_down[1] and ppo_up
ppo_change_down     = ppo_up[1] and ppo_down
ppo_stop_line :=
 ppo_up   ? ppo_lowerBB :
 ppo_down ? ppo_upperBB : na

ppo_bullishPrice = low

ppo_priceMins = ppo_bullishPrice > ppo_bullishPrice[1] and ppo_bullishPrice[1] < ppo_bullishPrice[2] or
   low[1] == low[2] and low[1] < low and low[1] < low[3] or
   low[1] == low[2] and low[1] == low[3] and low[1] < low and low[1] < low[4] or
   low[1] == low[2] and low[1] == low[3] and low[1] and low[1] == low[4] and
   low[1] < low and low[1] < low[5]  // this line identifies bottoms and plateaus in the price
ppo_oscMins = ppo_d > ppo_d[1] and ppo_d[1] < ppo_d[2]  // this line identifies bottoms in the PPO


ppo_BottomPointsInPPO = ppo_oscMins

ppo_bearishPrice = high
ppo_priceMax = ppo_bearishPrice < ppo_bearishPrice[1] and ppo_bearishPrice[1] > ppo_bearishPrice[2] or
   high[1] == high[2] and high[1] > high and high[1] > high[3] or
   high[1] == high[2] and high[1] == high[3] and high[1] > high and
   high[1] > high[4] or
   high[1] == high[2] and high[1] == high[3] and high[1] and high[1] == high[4] and
   high[1] > high and high[1] > high[5]  // this line identifies tops in the price
ppo_oscMax = ppo_d < ppo_d[1] and ppo_d[1] > ppo_d[2]  // this line identifies tops in the PPO

ppo_TopPointsInPPO = ppo_oscMax

ppo_buySignal = ppo_study_old ? ppo_BottomPointsInPPO and ta.barssince(ppo_BottomPointsInPPO)==0 and ppo_source > ppo_lowerBB and ppo_basis2 > ppo_source and close < ppo_vwapval : ppo_BottomPointsInPPO and ta.barssince(ppo_BottomPointsInPPO)==0 and ppo_source > ppo_lowerBB and ppo_basis2 > ppo_source and ppo_wasOversold_macdrsi
ppo_sellSignal = ppo_study_old ? ppo_TopPointsInPPO and ta.barssince(ppo_TopPointsInPPO)==0 and ppo_source < ppo_upperBB and ppo_source > ppo_basis2  and close > ppo_vwapval : ppo_TopPointsInPPO and ta.barssince(ppo_TopPointsInPPO)==0 and ppo_source < ppo_upperBB and ppo_source > ppo_basis2  and ppo_wasOverbought_macdrsi  // close > vwapval
ppo_close_long = ppo_sellSignal
ppo_close_short = ppo_buySignal

// *************************************************************************************************************************************************************************************************************************************************************************
// * STRATEGY 7: FURY
// *************************************************************************************************************************************************************************************************************************************************************************
fury_ma_function(_source, _atrlen) =>
    if fury_smoothing == 'RMA'
        ta.rma(_source, _atrlen)
    else
        if fury_smoothing == 'SMA'
            ta.sma(_source, _atrlen)
        else
            if fury_smoothing == 'EMA'
                ta.ema(_source, _atrlen)
            else
                ta.wma(_source, _atrlen)

fury_atr_slen = fury_ma_function(ta.tr(true), fury_atrlen)
////ATR Up/Low Bands
fury_upper_band = fury_atr_slen * fury_mult + close
fury_lower_band = close - fury_atr_slen * fury_mult

fury_tema(_src, _len) =>
    _ema1 = ta.ema(_src, _len)
    _ema2 = ta.ema(_ema1, _len)
    _ema3 = ta.ema(_ema2, _len)
    3 * _ema1 - 3 * _ema2 + _ema3

//EDSMA
fury_get2PoleSSF(_src, _length) =>
    _PI = 2 * math.asin(1)
    _arg = math.sqrt(2) * _PI / _length
    _a1 = math.exp(-_arg)
    _b1 = 2 * _a1 * math.cos(_arg)
    _c2 = _b1
    _c3 = -math.pow(_a1, 2)
    _c1 = 1 - _c2 - _c3

    _ssf = 0.0
    _ssf := _c1 * _src + _c2 * nz(_ssf[1]) + _c3 * nz(_ssf[2])
    _ssf

fury_get3PoleSSF(_src, _length) =>
    _PI = 2 * math.asin(1)

    _arg = _PI / _length
    _a1 = math.exp(-_arg)
    _b1 = 2 * _a1 * math.cos(1.738 * _arg)
    _c1 = math.pow(_a1, 2)

    _coef2 = _b1 + _c1
    _coef3 = -(_c1 + _b1 * _c1)
    _coef4 = math.pow(_c1, 2)
    _coef1 = 1 - _coef2 - _coef3 - _coef4

    _ssf = 0.0
    _ssf := _coef1 * _src + _coef2 * nz(_ssf[1]) + _coef3 * nz(_ssf[2]) + _coef4 * nz(_ssf[3])
    _ssf


fury_ma(_type, _src, _len) =>
    float _result = 0
    if _type == 'TMA'
        _result := ta.sma(ta.sma(_src, math.ceil(_len / 2)), math.floor(_len / 2) + 1)
        _result
    if _type == 'MF'
        _ts = 0.
        _b = 0.
        _c = 0.
        _os = 0.
        //----
        _alpha = 2 / (_len + 1)
        _a = fury_feedback ? fury_z * _src + (1 - fury_z) * nz(_ts[1], _src) : _src
        //----
        _b := _a > _alpha * _a + (1 - _alpha) * nz(_b[1], _a) ? _a : _alpha * _a + (1 - _alpha) * nz(_b[1], _a)
        _c := _a < _alpha * _a + (1 - _alpha) * nz(_c[1], _a) ? _a : _alpha * _a + (1 - _alpha) * nz(_c[1], _a)
        _os := _a == _b ? 1 : _a == _c ? 0 : _os[1]
        //----
        _upper = fury_beta * _b + (1 - fury_beta) * _c
        _lower = fury_beta * _c + (1 - fury_beta) * _b
        _ts := _os * _upper + (1 - _os) * _lower
        _result := _ts
        _result
    if _type == 'LSMA'
        _result := ta.linreg(_src, _len, 0)
        _result
    if _type == 'SMA'  // Simple
        _result := ta.sma(_src, _len)
        _result
    if _type == 'EMA'  // Exponential
        _result := ta.ema(_src, _len)
        _result
    if _type == 'DEMA'  // Double Exponential
        _e = ta.ema(_src, _len)
        _result := 2 * _e - ta.ema(_e, _len)
        _result
    if _type == 'TEMA'  // Triple Exponential
        _e = ta.ema(_src, _len)
        _result := 3 * (_e - ta.ema(_e, _len)) + ta.ema(ta.ema(_e, _len), _len)
        _result
    if _type == 'WMA'  // Weighted
        _result := ta.wma(_src, _len)
        _result
    if _type == 'VAMA'  // Volatility Adjusted
        /// Copyright Â© 2019 to present, Joris Duyck (JD)
        _mid = ta.ema(_src, _len)
        _dev = _src - _mid
        _vol_up = ta.highest(_dev, fury_volatility_lookback)
        _vol_down = ta.lowest(_dev, fury_volatility_lookback)
        _result := _mid + math.avg(_vol_up, _vol_down)
        _result
    if _type == 'HMA'  // Hull
        _result := ta.wma(2 * ta.wma(_src, _len / 2) - ta.wma(_src, _len), math.round(math.sqrt(_len)))
        _result
    if _type == 'JMA'  // Jurik
        /// Copyright Â© 2018 Alex Orekhov (everget)
        /// Copyright Â© 2017 Jurik Research and Consulting.
        _phaseRatio = fury_jurik_phase < -100 ? 0.5 : fury_jurik_phase > 100 ? 2.5 : fury_jurik_phase / 100 + 1.5
        _beta = 0.45 * (_len - 1) / (0.45 * (_len - 1) + 2)
        _alpha = math.pow(_beta, fury_jurik_power)
        _jma = 0.0
        _e0 = 0.0
        _e0 := (1 - _alpha) * _src + _alpha * nz(_e0[1])
        _e1 = 0.0
        _e1 := (_src - _e0) * (1 - _beta) + _beta * nz(_e1[1])
        _e2 = 0.0
        _e2 := (_e0 + _phaseRatio * _e1 - nz(_jma[1])) * math.pow(1 - _alpha, 2) + math.pow(_alpha, 2) * nz(_e2[1])
        _jma := _e2 + nz(_jma[1])
        _result := _jma
        _result
    if _type == 'Kijun v2'
        _kijun = math.avg(ta.lowest(_len), ta.highest(_len))  //, (open + close)/2)
        _conversionLine = math.avg(ta.lowest(_len / fury_kidiv), ta.highest(_len / fury_kidiv))
        _delta = (_kijun + _conversionLine) / 2
        _result := _delta
        _result
    if _type == 'McGinley'
        _mg = 0.0
        _mg := na(_mg[1]) ? ta.ema(_src, _len) : _mg[1] + (_src - _mg[1]) / (_len * math.pow(_src / _mg[1], 4))
        _result := _mg
        _result
    if _type == 'EDSMA'

        _zeros = _src - nz(_src[2])
        _avgZeros = (_zeros + _zeros[1]) / 2

        // Ehlers Super Smoother Filter
        _ssf = fury_ssfPoles == 2 ? fury_get2PoleSSF(_avgZeros, fury_ssfLength) : fury_get3PoleSSF(_avgZeros, fury_ssfLength)

        // Rescale filter in terms of Standard Deviations
        _stdev = ta.stdev(_ssf, _len)
        _scaledFilter = _stdev != 0 ? _ssf / _stdev : 0

        _alpha = 5 * math.abs(_scaledFilter) / _len

        _edsma = 0.0
        _edsma := _alpha * _src + (1 - _alpha) * nz(_edsma[1])
        _result := _edsma
        _result
    _result

///SSL 1 and SSL2
fury_emaHigh = fury_ma(fury_maType, high, fury_len)
fury_emaLow = fury_ma(fury_maType, low, fury_len)

//SSL1 VALUES
fury_Hlv = int(na)
fury_Hlv := close > fury_emaHigh ? 1 : close < fury_emaLow ? -1 : fury_Hlv[1]
fury_sslDown = fury_Hlv < 0 ? fury_emaHigh : fury_emaLow

fury_getstsource(_type)=>
    switch _type
    	"SSL1" => fury_sslDown
    	"hl2c/4" => (high + low + 2 * close) / 4
    	"hc/2" => close > open ? (high + close) / 2 : (low + close) / 2
    	// Default used when the three first cases do not match.
    	=> hl2

fury_stsrc = fury_getstsource(fury_stsource)
fury_atr2 = ta.sma(ta.tr, fury_Periods)
fury_atr = fury_changeATR ? ta.atr(fury_Periods) : fury_atr2
fury_up = fury_stsrc - fury_Multiplier * fury_atr
fury_up1 = nz(fury_up[1], fury_up)
fury_up := close[1] > fury_up1 ? math.max(fury_up, fury_up1) : fury_up
fury_dn = fury_stsrc + fury_Multiplier * fury_atr
fury_dn1 = nz(fury_dn[1], fury_dn)
fury_dn := close[1] < fury_dn1 ? math.min(fury_dn, fury_dn1) : fury_dn
fury_trend = 1
fury_trend := nz(fury_trend[1], fury_trend)
fury_trend := fury_trend == -1 and close > fury_dn1 ? 1 : fury_trend == 1 and close < fury_up1 ? -1 : fury_trend

fury_buySignal = fury_trend == 1 and fury_trend[1] == -1
fury_sellSignal = fury_trend == -1 and fury_trend[1] == 1
fury_close_long = fury_sellSignal
fury_close_short = fury_buySignal

// *************************************************************************************************************************************************************************************************************************************************************************
// * STRATEGY 6: POTENTIAL TOP/BOTTOM
// *************************************************************************************************************************************************************************************************************************************************************************
// * Combination RSI, Stoch RSI, MACD, volume, and weighted-strategy to detect potential TOP/BOTTOMS areas
volumeRSI_condition = volume[2] > volume[3] and volume[2] > volume[4] and volume[2] > volume[5]
condition_OB1 = isRsiOB2 and (isRsiOB or volume < ma('SMA', volume, 20) / 2) and volumeRSI_condition
condition_OS1 = isRsiOS2 and (isRsiOS or volume < ma('SMA', volume, 20) / 2) and volumeRSI_condition

condition_OB2 = volume[2] / volume[1] > (1.0 + long_trail_perc) and isRsiOB and volumeRSI_condition
condition_OS2 = volume[2] / volume[1] > (1.0 + short_trail_perc) and isRsiOS and volumeRSI_condition

condition_OB3 = weight_total(MACD < signal, isRsiOB, isRsiOB2, short4, short5, true, true) >= weight_trigger
condition_OS3 = weight_total(MACD > signal, isRsiOS, isRsiOS2, long4, long5, true, true) >= weight_trigger

condition_OB = (condition_OB1 or condition_OB2)
condition_OS = (condition_OS1 or condition_OS2)
condition_OB_several = condition_OB[1] and condition_OB[2] or condition_OB[1] and condition_OB[3] or condition_OB[1] and condition_OB[4] or condition_OB[1] and condition_OB[5] or condition_OB[1] and condition_OB[6] or condition_OB[1] and condition_OB[7]
condition_OS_several = condition_OS[1] and condition_OS[2] or condition_OS[1] and condition_OS[3] or condition_OS[1] and condition_OS[4] or condition_OS[1] and condition_OS[5] or condition_OS[1] and condition_OS[6] or condition_OS[1] and condition_OS[7]


// *************************************************************************************************************************************************************************************************************************************************************************
// STRATEGY ENTRIES AND EXITS
// *************************************************************************************************************************************************************************************************************************************************************************
long_condition = false
close_long_condition = false
partial_close_long_condition = false
short_condition = false
close_short_condition = false
partial_close_short_condition = false

if time >= start and time <= end
    // ***************************************************************************************************************************************************************************
    // * Set Entries
    // ***************************************************************************************************************************************************************************
    if str_0
        if not str_1
            weight_str1 := 0
        if not str_2
            weight_str2 := 0
        if not str_3
            weight_str3 := 0
        if not str_4
            weight_str4 := 0
        if not str_5
            weight_str5 := 0
        if not str_6
            weight_str6 := 0
        if not str_7
            weight_str7 := 0
        if allow_shorts == true
            w_total = weight_total(short_signal1, short_signal2, short_signal3, short_signal4, short_signal5, ppo_sellSignal, fury_sellSignal)
            if w_total >= weight_trigger and realtime_cond
                short_condition := true
                strategy.entry('Short', strategy.short, alert_message=alarm_label_short)
        if allow_longs == true
            w_total = weight_total(long_signal1, long_signal2, long_signal3, long_signal4, long_signal5, ppo_buySignal, fury_buySignal)
            if w_total >= weight_trigger and realtime_cond
                long_condition := true
                strategy.entry('Long', strategy.long, alert_message=alarm_label_long)
    else
        if allow_shorts == true and realtime_cond
            if str_1
                short_condition := short_signal1
                strategy.entry('Short', strategy.short, when=short_signal1, alert_message=alarm_label_short)
            if str_2
                short_condition := short_condition ? true : short_signal2
                strategy.entry('Short', strategy.short, when=short_signal2, alert_message=alarm_label_short)
            if str_3
                short_condition := short_condition ? true : short_signal3
                strategy.entry('Short', strategy.short, when=short_signal3, alert_message=alarm_label_short)
            if str_4
                short_condition := short_condition ? true : short_signal4
                strategy.entry('Short', strategy.short, when=short_signal4, alert_message=alarm_label_short)
            if str_5
                short_condition := short_condition ? true : short_signal5
                strategy.entry('Short', strategy.short, when=short_signal5, alert_message=alarm_label_short)
            if str_6
                short_condition := short_condition ? true : ppo_sellSignal
                strategy.entry('Short', strategy.short, when=ppo_sellSignal, alert_message=alarm_label_short)
            if str_7
                short_condition := short_condition ? true : fury_sellSignal
                strategy.entry('Short', strategy.short, when=fury_sellSignal, alert_message=alarm_label_short)
        if allow_longs == true and realtime_cond
            if str_1
                long_condition := long_signal1
                strategy.entry('Long', strategy.long, when=long_signal1, alert_message=alarm_label_long)
            if str_2
                long_condition := long_condition ? true : long_signal2
                strategy.entry('Long', strategy.long, when=long_signal2, alert_message=alarm_label_long)
            if str_3
                long_condition := long_condition ? true : long_signal3
                strategy.entry('Long', strategy.long, when=long_signal3, alert_message=alarm_label_long)
            if str_4
                long_condition := long_condition ? true : long_signal4
                strategy.entry('Long', strategy.long, when=long_signal4, alert_message=alarm_label_long)
            if str_5
                long_condition := long_condition ? true : long_signal5
                strategy.entry('Long', strategy.long, when=long_signal5, alert_message=alarm_label_long)
            if str_6
                long_condition := long_condition ? true : ppo_buySignal
                strategy.entry('Long', strategy.long, when=ppo_buySignal, alert_message=alarm_label_long)
            if str_7
                long_condition := long_condition ? true : fury_buySignal
                strategy.entry('Long', strategy.long, when=fury_buySignal, alert_message=alarm_label_long)
    // ***************************************************************************************************************************************************************************
    // * Set Take Profits
    // ***************************************************************************************************************************************************************************
    if strategy.position_size != 0 and take_profits and since_entry == 0
        for i = 1 to MAX_TP
            id = 'TP ' + str.tostring(i)
            strategy.exit(id=id, limit=price_takeProfit(profit_perc, i), qty_percent=profit_qty, comment=id, alert_message=set_alarm_label_TP())
    // ***************************************************************************************************************************************************************************
    // * Set Stop loss
    // ***************************************************************************************************************************************************************************
    if strategy.position_size > 0
        if since_close == 0
            if high > price_takeProfit(profit_perc, 6) and MAX_TP >= 6
                n = 6
                nextTP := na
                if movestoploss == 'Percentage'
                    price_stop_long := strategy.position_avg_price * (1 + n*profit_perc - stoploss_perc * move_stoploss_factor)
                else if movestoploss == 'TP-1'
                    price_stop_long := price_takeProfit(profit_perc, n-1)
                else if movestoploss == 'TP-2'
                    price_stop_long := price_takeProfit(profit_perc, n-2)
                else if movestoploss == 'TP-3'
                    price_stop_long := price_takeProfit(profit_perc, n-3)
            else if high > price_takeProfit(profit_perc, 5) and MAX_TP >= 5
                n = 5
                nextTP := price_takeProfit(profit_perc, n + 1)
                if movestoploss == 'Percentage'
                    price_stop_long := strategy.position_avg_price * (1 + n*profit_perc - stoploss_perc * move_stoploss_factor)
                else if movestoploss == 'TP-1'
                    price_stop_long := price_takeProfit(profit_perc, n-1)
                else if movestoploss == 'TP-2'
                    price_stop_long := price_takeProfit(profit_perc, n-2)
                else if movestoploss == 'TP-3'
                    price_stop_long := price_takeProfit(profit_perc, n-3)
            else if high > price_takeProfit(profit_perc, 4) and MAX_TP >= 4
                n = 4
                nextTP := price_takeProfit(profit_perc, n + 1)
                if movestoploss == 'Percentage'
                    price_stop_long := strategy.position_avg_price * (1 + n*profit_perc - stoploss_perc * move_stoploss_factor)
                else if movestoploss == 'TP-1'
                    price_stop_long := price_takeProfit(profit_perc, n-1)
                else if movestoploss == 'TP-2'
                    price_stop_long := price_takeProfit(profit_perc, n-2)
                else if movestoploss == 'TP-3'
                    price_stop_long := price_takeProfit(profit_perc, n-3)
            else if high > price_takeProfit(profit_perc, 3) and MAX_TP >= 3
                n = 3
                nextTP := price_takeProfit(profit_perc, n + 1)
                if movestoploss == 'Percentage'
                    price_stop_long := strategy.position_avg_price * (1 + n*profit_perc - stoploss_perc * move_stoploss_factor)
                else if movestoploss == 'TP-1'
                    price_stop_long := price_takeProfit(profit_perc, n-1)
                else if movestoploss == 'TP-2'
                    price_stop_long := price_takeProfit(profit_perc, n-2)
                else if movestoploss == 'TP-3' and movestoploss_entry
                    price_stop_long := strategy.position_avg_price
            else if high > price_takeProfit(profit_perc, 2) and MAX_TP >= 2
                n = 2
                nextTP := price_takeProfit(profit_perc, n + 1)
                if movestoploss == 'Percentage'
                    price_stop_long := strategy.position_avg_price * (1 + n*profit_perc - stoploss_perc * move_stoploss_factor)
                else if movestoploss == 'TP-1'
                    price_stop_long := price_takeProfit(profit_perc, n-1)
                else if movestoploss == 'TP-2' and movestoploss_entry
                    price_stop_long := strategy.position_avg_price
                else if movestoploss == 'TP-3' and movestoploss_entry
                    price_stop_long := strategy.position_avg_price
            else if high > price_takeProfit(profit_perc, 1) and MAX_TP >= 1
                n = 1
                nextTP := price_takeProfit(profit_perc, n + 1)
                if movestoploss == 'Percentage'
                    price_stop_long := strategy.position_avg_price * (1 + n*profit_perc - stoploss_perc * move_stoploss_factor)
                else if movestoploss == 'TP-1' and movestoploss_entry
                    price_stop_long := strategy.position_avg_price
                else if movestoploss == 'TP-2' and movestoploss_entry
                    price_stop_long := strategy.position_avg_price
                else if movestoploss == 'TP-3' and movestoploss_entry
                    price_stop_long := strategy.position_avg_price
        if since_entry == 0
            n = 0
            nextTP := price_takeProfit(profit_perc, n + 1)
            price_stop_long := strategy.position_avg_price * (1 - stoploss_perc)
    if strategy.position_size < 0
        if since_close == 0
            if low < price_takeProfit(profit_perc, 6) and MAX_TP >= 6
                n = 6
                nextTP := na
                if movestoploss == 'Percentage'
                    price_stop_short := strategy.position_avg_price * (1 - n*profit_perc + stoploss_perc * move_stoploss_factor)
                else if movestoploss == 'TP-1'
                    price_stop_short := price_takeProfit(profit_perc, n-1)
                else if movestoploss == 'TP-2'
                    price_stop_short := price_takeProfit(profit_perc, n-2)
                else if movestoploss == 'TP-3'
                    price_stop_short := price_takeProfit(profit_perc, n-3)
            else if low < price_takeProfit(profit_perc, 5) and MAX_TP >= 5
                n = 5
                nextTP := price_takeProfit(profit_perc, n + 1)
                if movestoploss == 'Percentage'
                    price_stop_short := strategy.position_avg_price * (1 - n*profit_perc + stoploss_perc * move_stoploss_factor)
                else if movestoploss == 'TP-1'
                    price_stop_short := price_takeProfit(profit_perc, n-1)
                else if movestoploss == 'TP-2'
                    price_stop_short := price_takeProfit(profit_perc, n-2)
                else if movestoploss == 'TP-3'
                    price_stop_short := price_takeProfit(profit_perc, n-3)
            else if low < price_takeProfit(profit_perc, 4) and MAX_TP >= 4
                n = 4
                nextTP := price_takeProfit(profit_perc, n + 1)
                if movestoploss == 'Percentage'
                    price_stop_short := strategy.position_avg_price * (1 - n*profit_perc + stoploss_perc * move_stoploss_factor)
                else if movestoploss == 'TP-1'
                    price_stop_short := price_takeProfit(profit_perc, n-1)
                else if movestoploss == 'TP-2'
                    price_stop_short := price_takeProfit(profit_perc, n-2)
                else if movestoploss == 'TP-3'
                    price_stop_short := price_takeProfit(profit_perc, n-3)
            else if low < price_takeProfit(profit_perc, 3) and MAX_TP >= 3
                n = 3
                nextTP := price_takeProfit(profit_perc, n + 1)
                if movestoploss == 'Percentage'
                    price_stop_short := strategy.position_avg_price * (1 - n*profit_perc + stoploss_perc * move_stoploss_factor)
                else if movestoploss == 'TP-1'
                    price_stop_short := price_takeProfit(profit_perc, n-1)
                else if movestoploss == 'TP-2'
                    price_stop_short := price_takeProfit(profit_perc, n-2)
                else if movestoploss == 'TP-3' and movestoploss_entry
                    price_stop_short := strategy.position_avg_price
            else if low < price_takeProfit(profit_perc, 2) and MAX_TP >= 2
                n = 2
                nextTP := price_takeProfit(profit_perc, n + 1)
                if movestoploss == 'Percentage'
                    price_stop_short := strategy.position_avg_price * (1 - n*profit_perc + stoploss_perc * move_stoploss_factor)
                else if movestoploss == 'TP-1'
                    price_stop_short := price_takeProfit(profit_perc, n-1)
                else if movestoploss == 'TP-2' and movestoploss_entry
                    price_stop_short := strategy.position_avg_price
                else if movestoploss == 'TP-3' and movestoploss_entry
                    price_stop_short := strategy.position_avg_price
            else if low < price_takeProfit(profit_perc, 1) and MAX_TP >= 1
                n = 1
                nextTP := price_takeProfit(profit_perc, n + 1)
                if movestoploss == 'Percentage'
                    price_stop_short := strategy.position_avg_price * (1 - n*profit_perc + stoploss_perc * move_stoploss_factor)
                else if movestoploss == 'TP-1' and movestoploss_entry
                    price_stop_short := strategy.position_avg_price
                else if movestoploss == 'TP-2' and movestoploss_entry
                    price_stop_short := strategy.position_avg_price
                else if movestoploss == 'TP-3' and movestoploss_entry
                    price_stop_short := strategy.position_avg_price
        if since_entry == 0
            n = 0
            nextTP := price_takeProfit(profit_perc, n + 1)
            price_stop_short := strategy.position_avg_price * (1 + stoploss_perc)
    // ***************************************************************************************************************************************************************************
    // * Set Exits
    // ***************************************************************************************************************************************************************************
    if allow_longs == true and allow_shorts == false
        if str_0
            w_total = weight_total(short_signal1, short_signal2, short_signal3, short_signal4, short_signal5, ppo_sellSignal, fury_sellSignal)
            close_long_condition := w_total>=weight_trigger
            strategy.close('Long', when=w_total>=weight_trigger, qty_percent=100, comment='SHORT', alert_message=alarm_label_close_long)
        else
            if str_1
                close_long_condition := close_long1
                strategy.close('Long', when=close_long1, qty_percent=100, comment='SHORT', alert_message=alarm_label_close_long)
            if str_2
                close_long_condition := close_long_condition ? true : close_long2
                strategy.close('Long', when=close_long2, qty_percent=100, comment='SHORT', alert_message=alarm_label_close_long)
            if str_3
                close_long_condition := close_long_condition ? true : close_long3
                strategy.close('Long', when=close_long3, qty_percent=100, comment='SHORT', alert_message=alarm_label_close_long)
            if str_4
                close_long_condition := close_long_condition ? true : close_long4
                strategy.close('Long', when=close_long4, qty_percent=100, comment='SHORT', alert_message=alarm_label_close_long)
            if str_5
                close_long_condition := close_long_condition ? true : close_long5
                strategy.close('Long', when=close_long5, qty_percent=100, comment='SHORT', alert_message=alarm_label_close_long)
            if str_6
                close_long_condition := close_long_condition ? true : ppo_close_long
                strategy.close('Long', when=ppo_close_long, qty_percent=100, comment='SHORT', alert_message=alarm_label_close_long)
            if str_7
                close_long_condition := close_long_condition ? true : fury_close_long
                strategy.close('Long', when=fury_close_long, qty_percent=100, comment='SHORT', alert_message=alarm_label_close_long)
    if allow_longs == false and allow_shorts == true
        if str_0
            w_total = weight_total(long_signal1, long_signal2, long_signal3, long_signal4, long_signal5, ppo_buySignal, fury_buySignal)
            close_short_condition := w_total>=weight_trigger
            strategy.close('Short', when=w_total>=weight_trigger, qty_percent=100, comment='LONG', alert_message=alarm_label_close_short)
        else
            if str_1
                close_short_condition := close_short1
                strategy.close('Short', when=close_short1, qty_percent=100, comment='LONG', alert_message=alarm_label_close_short)
            if str_2
                close_short_condition := close_short_condition ? true : close_short2
                strategy.close('Short', when=close_short2, qty_percent=100, comment='LONG', alert_message=alarm_label_close_short)
            if str_3
                close_short_condition := close_short_condition ? true : close_short3
                strategy.close('Short', when=close_short3, qty_percent=100, comment='LONG', alert_message=alarm_label_close_short)
            if str_4
                close_short_condition := close_short_condition ? true : close_short4
                strategy.close('Short', when=close_short4, qty_percent=100, comment='LONG', alert_message=alarm_label_close_short)
            if str_5
                close_short_condition := close_short_condition ? true : close_short5
                strategy.close('Short', when=close_short5, qty_percent=100, comment='LONG', alert_message=alarm_label_close_short)
            if str_6
                close_short_condition := close_short_condition ? true : ppo_close_short
                strategy.close('Short', when=ppo_close_short, qty_percent=100, comment='LONG', alert_message=alarm_label_close_short)
            if str_7
                close_short_condition := close_short_condition ? true : fury_close_short
                strategy.close('Short', when=fury_close_short, qty_percent=100, comment='LONG', alert_message=alarm_label_close_short)
    if allow_shorts == true and strategy.position_size < 0 and stoploss and since_entry > 0
        strategy.close('Short', when=stop_source >= price_stop_short, qty_percent=100, comment='STOP', alert_message=alarm_label_SL)
        if str_8
            partial_close_short_condition := condition_OS_several
            if top_qty == 100
                strategy.close('Short', when=condition_OS_several, qty_percent=bottom_qty, comment='STOP', alert_message=alarm_label_SL)
            else
                strategy.exit('Short', when=condition_OS_several, limit=source_6_bottom[1], qty_percent=bottom_qty, comment='TP-B', alert_message=set_alarm_label_TP())
    if allow_longs == true and strategy.position_size > 0 and stoploss and since_entry > 0
        strategy.close('Long', when=stop_source <= price_stop_long, qty_percent=100, comment='STOP', alert_message=alarm_label_SL)
        if str_8
            partial_close_long_condition := condition_OB_several
            if top_qty == 100
                strategy.close('Long', when=condition_OB_several, qty_percent=top_qty, comment='STOP', alert_message=alarm_label_SL)
            else
                strategy.exit('Long', when=condition_OB_several, limit=source_6_top[1], qty_percent=top_qty, comment='TP-T', alert_message=set_alarm_label_TP())
// *************************************************************************************************************************************************************************************************************************************************************************
// * Data window - debugging
// *************************************************************************************************************************************************************************************************************************************************************************
price_stop = strategy.position_size > 0 ? price_stop_long : price_stop_short

plotchar(volume[2] / volume[1], "Volume 2 / Volume 1", "", location.top, size = size.tiny, color=color.new(color.orange, 0))
plotchar(since_entry, "Since entry [bars]", "", location.top, size = size.tiny, color=color.new(color.orange, 0))
plotchar(since_close, "Since close/TP [bars]", "", location.top, size = size.tiny, color=color.new(color.orange, 0))
plotchar(strategy.position_avg_price, "Average position price", "", location.top, size = size.tiny, color=color.new(color.orange, 0))
plotchar(strategy.position_size, "Position size", "", location.top, size = size.tiny, color=color.new(color.orange, 0))
plotchar(nextTP, "Next TP target", "", location.top, size = size.tiny, color=color.new(color.teal, 0))
plotchar(price_stop, "STOP Price", "", location.top, size = size.tiny, color=color.new(color.gray, 0))
plotchar(strategy.opentrades, "Open trades", "", location.top, size = size.tiny, color=strategy.position_size > 0 ? color.blue : color.gray)
plotchar(strategy.netprofit, "Net profit [$]", "", location.top, size = size.tiny, color=strategy.netprofit > 0 ? color.blue : color.gray)
plotchar(strategy.grossprofit, "Gross profit [$]", "", location.top, size = size.tiny, color=color.blue)
plotchar(strategy.grossloss, "Gross loss [$]", "", location.top, size = size.tiny, color=color.gray)
plotchar(strategy.openprofit, "Unrealized P&L [$]", "", location.top, size = size.tiny, color=strategy.openprofit > 0 ? color.blue : color.gray)
plotchar(strategy.closedtrades, "Closed trades", "", location.top, size = size.tiny, color=color.orange)
plotchar(strategy.wintrades/strategy.closedtrades*100, "Winrate [%]", "", location.top, size = size.tiny, color=strategy.wintrades/strategy.closedtrades > 60 ? color.blue : color.gray)
// *************************************************************************************************************************************************************************************************************************************************************************
// PLOTS
// *************************************************************************************************************************************************************************************************************************************************************************
// * strategy 1: MACD
// *************************************************************************************************************************************************************************************************************************************************************************
plot(trend, 'Trend', style=plot.style_columns, color=MACD > signal ? color.new(color.teal, 30) : color.new(color.gray, 30), display=display.none)
plot(MACD, 'MACD', color=color.new(color.blue, 0), display=display.none)
plot(signal, 'Signal', color=color.new(color.orange, 0), display=display.none)
plotshape(long_signal1 and FLAG_SIGNALS ? up : na, 'Buy MACD', text='MACD', location=location.absolute, style=shape.labelup, size=size.tiny, color=color.new(color.teal, 0), textcolor=color.new(color.white, 0), display=display.none)
plotshape(short_signal1 and FLAG_SIGNALS ? dn : na, 'Sell MACD', text='MACD', location=location.absolute, style=shape.labeldown, size=size.tiny, color=color.new(color.gray, 0), textcolor=color.new(color.white, 0), display=display.none)
// *************************************************************************************************************************************************************************************************************************************************************************
// * strategy 2: Stoch RSI
// *************************************************************************************************************************************************************************************************************************************************************************
plotshape(long_signal2 and FLAG_SIGNALS ? up : na, title='Buy Stoch RSI', text='SRSI', location=location.absolute, style=shape.labelup, size=size.tiny, color=color.new(color.teal, 0), textcolor=color.new(color.white, 0), display=display.none)
plotshape(short_signal2 and FLAG_SIGNALS ? dn : na, title='Sell Stoch RSI', text='SRSI', location=location.absolute, style=shape.labeldown, size=size.tiny, color=color.new(color.gray, 0), textcolor=color.new(color.white, 0), display=display.none)
// *************************************************************************************************************************************************************************************************************************************************************************
// * strategy 3: RSI
// *************************************************************************************************************************************************************************************************************************************************************************
plotshape(long_signal3 and FLAG_SIGNALS ? up : na, title='Buy RSI', text='RSI', location=location.absolute, style=shape.labelup, size=size.tiny, color=color.new(color.teal, 0), textcolor=color.new(color.white, 0), display=display.none)
plotshape(short_signal3 and FLAG_SIGNALS ? dn : na, title='Sell RSI', text='RSI', location=location.absolute, style=shape.labeldown, size=size.tiny, color=color.new(color.gray, 0), textcolor=color.new(color.white, 0), display=display.none)
// *************************************************************************************************************************************************************************************************************************************************************************
// * strategy 4: Supertrend
// *************************************************************************************************************************************************************************************************************************************************************************
plotshape(long_signal4 and FLAG_SIGNALS ? up : na, title='Buy Supertrend', text='Supertrend', location=location.absolute, style=shape.labelup, size=size.tiny, color=color.new(color.teal, 0), textcolor=color.new(color.white, 0), display=display.none)
plotshape(short_signal4 and FLAG_SIGNALS ? dn : na, title='Sell Supertrend', text='Supertrend', location=location.absolute, style=shape.labeldown, size=size.tiny, color=color.new(color.gray, 0), textcolor=color.new(color.white, 0), display=display.none)
// *************************************************************************************************************************************************************************************************************************************************************************
// * strategy 5: MA CROSS
// *************************************************************************************************************************************************************************************************************************************************************************
plotshape(long_signal5 and FLAG_SIGNALS ? up : na, title='Buy MA CROSS', text='MA CROSS', location=location.absolute, style=shape.labelup, size=size.tiny, color=color.new(color.teal, 0), textcolor=color.new(color.white, 0), display=display.none)
plotshape(short_signal5 and FLAG_SIGNALS ? dn : na, title='Sell MA CROSS', text='MA CROSS', location=location.absolute, style=shape.labeldown, size=size.tiny, color=color.new(color.gray, 0), textcolor=color.new(color.white, 0), display=display.none)
// *************************************************************************************************************************************************************************************************************************************************************************
// * strategy 6: PPO
// *************************************************************************************************************************************************************************************************************************************************************************
plotshape(ppo_buySignal and FLAG_SIGNALS ? up : na, title='Buy PPO', text='PPO', location=location.absolute, style=shape.labelup, size=size.tiny, color=color.new(color.teal, 0), textcolor=color.new(color.white, 0), display=display.none)
plotshape(ppo_sellSignal and FLAG_SIGNALS ? dn : na, title='Sell PPO', text='PPO', location=location.absolute, style=shape.labeldown, size=size.tiny, color=color.new(color.gray, 0), textcolor=color.new(color.white, 0), display=display.none)
// *************************************************************************************************************************************************************************************************************************************************************************
// * strategy 7: FURY
// *************************************************************************************************************************************************************************************************************************************************************************
plotshape(fury_buySignal and FLAG_SIGNALS ? up : na, title='Buy FURY', text='FURY', location=location.absolute, style=shape.labelup, size=size.tiny, color=color.new(color.teal, 0), textcolor=color.new(color.white, 0), display=display.none)
plotshape(fury_sellSignal and FLAG_SIGNALS ? dn : na, title='Sell FURY', text='FURY', location=location.absolute, style=shape.labeldown, size=size.tiny, color=color.new(color.gray, 0), textcolor=color.new(color.white, 0), display=display.none)
// *************************************************************************************************************************************************************************************************************************************************************************
// * STRATEGY 8: POTENTIAL TOP/BOTTOM
// *************************************************************************************************************************************************************************************************************************************************************************
plotshape(condition_OB_several ? dn : na, title='Top', text='T', location=location.abovebar, style=shape.labeldown, size=size.tiny, color=color.new(color.teal, 0), textcolor=color.new(color.white, 0))
plotshape(condition_OS_several ? up : na, title='Bottom', text='B', location=location.belowbar, style=shape.labelup, size=size.tiny, color=color.new(color.teal, 0), textcolor=color.new(color.white, 0))
// *************************************************************************************************************************************************************************************************************************************************************************
// * Buy/Sell signals
// *************************************************************************************************************************************************************************************************************************************************************************
w_total_long = weight_total(long_signal1, long_signal2, long_signal3, long_signal4, long_signal5, ppo_buySignal, fury_buySignal)
w_total_short = weight_total(short_signal1, short_signal2, short_signal3, short_signal4, short_signal5, ppo_sellSignal, fury_sellSignal)
plotshape(w_total_long >= weight_trigger and FLAG_SIGNALS ? up : na, title='Buy Weigthed strategy', text='Buy', location=location.absolute, style=shape.labelup, size=size.tiny, color=color.new(color.teal, 0), textcolor=color.new(color.white, 0))
plotshape(w_total_short >= weight_trigger and FLAG_SIGNALS ? dn : na, title='Sell Weigthed strategy', text='Sell', location=location.absolute, style=shape.labeldown, size=size.tiny, color=color.new(color.gray, 0), textcolor=color.new(color.white, 0))
// *************************************************************************************************************************************************************************************************************************************************************************
// * Stop loss targets
// *************************************************************************************************************************************************************************************************************************************************************************
plot(series=(strategy.position_size > 0) ? price_stop_long : na, color=color.new(color.gray, 30), style=plot.style_cross, linewidth=2, title="Long Stop Loss")
plot(series=(strategy.position_size < 0) ? price_stop_short : na, color=color.new(color.gray, 30), style=plot.style_cross, linewidth=2, title="Short Stop Loss")
// *************************************************************************************************************************************************************************************************************************************************************************
// * TP targets
// *************************************************************************************************************************************************************************************************************************************************************************
plot(strategy.position_size > 0 or strategy.position_size < 0 ? nextTP : na, color=color.new(color.aqua, 30), style=plot.style_cross, linewidth=2, title="Next TP")
// *************************************************************************************************************************************************************************************************************************************************************************
// * All strategies
// *************************************************************************************************************************************************************************************************************************************************************************
mPlot = plot(ohlc4, title='Price ohlc4', style=plot.style_circles, linewidth=0, display=display.none)
upPlot = plot((long_signal1 or long_signal2 or long_signal3 or long_signal4 or long_signal5) and (w_total_long > w_total_short) ? up : na, title='Up Trend', style=plot.style_linebr, linewidth=2, color=color.new(color.aqua, 0), display=display.none)
dnPlot = plot((short_signal1 or short_signal2 or short_signal3 or short_signal4 or short_signal5) and (w_total_short > w_total_long) ? dn : na, title='Down Trend', style=plot.style_linebr, linewidth=2, color=color.new(color.gray, 0), display=display.none)
plotchar(weight_trigger, "Trigger strategies", "", location.top, size = size.tiny, color=color.new(color.orange, 0))
plotchar(w_total_long, "Satisfied Long strategies", "", location.top, size = size.tiny, color=w_total_long >= weight_trigger ? color.orange : color.gray)
plotchar(w_total_short, "Satisfied Short strategies", "", location.top, size = size.tiny, color=w_total_long >= weight_trigger ? color.orange : color.gray)
plotshape((long_signal1 or long_signal2 or long_signal3 or long_signal4 or long_signal5) and (w_total_long > w_total_short) ? up : na, title='UpTrend Begins', location=location.absolute, style=shape.circle, size=size.tiny, color=color.new(color.aqua, 0), display=display.none)
plotshape((short_signal1 or short_signal2 or short_signal3 or short_signal4 or short_signal5) and (w_total_short > w_total_long) ? dn : na, title='DownTrend Begins', location=location.absolute, style=shape.circle, size=size.tiny, color=color.new(color.gray, 0), display=display.none)
fill(mPlot, upPlot, title='UpTrend Highligter', color=colors('buy', FLAG_SHADOWS ? 80:100))
fill(mPlot, dnPlot, title='DownTrend Highligter', color=colors('sell', FLAG_SHADOWS ? 80:100))
// *************************************************************************************************************************************************************************************************************************************************************************
// MONTHLY TABLE PERFORMANCE - Developed by @QuantNomad
// *************************************************************************************************************************************************************************************************************************************************************************
show_performance = input.bool(true, 'Show Monthly Performance ?', group='Performance - credits: @QuantNomad')
prec = input(2, 'Return Precision', group='Performance - credits: @QuantNomad')

if show_performance
    new_month = month(time) != month(time[1])
    new_year  = year(time)  != year(time[1])

    eq = strategy.equity

    bar_pnl = eq / eq[1] - 1

    cur_month_pnl = 0.0
    cur_year_pnl  = 0.0

    // Current Monthly P&L
    cur_month_pnl := new_month ? 0.0 :
                     (1 + cur_month_pnl[1]) * (1 + bar_pnl) - 1

    // Current Yearly P&L
    cur_year_pnl := new_year ? 0.0 :
                     (1 + cur_year_pnl[1]) * (1 + bar_pnl) - 1

    // Arrays to store Yearly and Monthly P&Ls
    var month_pnl  = array.new_float(0)
    var month_time = array.new_int(0)

    var year_pnl  = array.new_float(0)
    var year_time = array.new_int(0)

    last_computed = false

    if (not na(cur_month_pnl[1]) and (new_month or barstate.islastconfirmedhistory))
        if (last_computed[1])
            array.pop(month_pnl)
            array.pop(month_time)

        array.push(month_pnl , cur_month_pnl[1])
        array.push(month_time, time[1])

    if (not na(cur_year_pnl[1]) and (new_year or barstate.islastconfirmedhistory))
        if (last_computed[1])
            array.pop(year_pnl)
            array.pop(year_time)

        array.push(year_pnl , cur_year_pnl[1])
        array.push(year_time, time[1])

    last_computed := barstate.islastconfirmedhistory ? true : nz(last_computed[1])

    // Monthly P&L Table
    var monthly_table = table(na)

    if (barstate.islastconfirmedhistory)
        monthly_table := table.new(position.bottom_right, columns = 14, rows = array.size(year_pnl) + 1, border_width = 1)

        table.cell(monthly_table, 0,  0, "",     bgcolor = #cccccc)
        table.cell(monthly_table, 1,  0, "Jan",  bgcolor = #cccccc)
        table.cell(monthly_table, 2,  0, "Feb",  bgcolor = #cccccc)
        table.cell(monthly_table, 3,  0, "Mar",  bgcolor = #cccccc)
        table.cell(monthly_table, 4,  0, "Apr",  bgcolor = #cccccc)
        table.cell(monthly_table, 5,  0, "May",  bgcolor = #cccccc)
        table.cell(monthly_table, 6,  0, "Jun",  bgcolor = #cccccc)
        table.cell(monthly_table, 7,  0, "Jul",  bgcolor = #cccccc)
        table.cell(monthly_table, 8,  0, "Aug",  bgcolor = #cccccc)
        table.cell(monthly_table, 9,  0, "Sep",  bgcolor = #cccccc)
        table.cell(monthly_table, 10, 0, "Oct",  bgcolor = #cccccc)
        table.cell(monthly_table, 11, 0, "Nov",  bgcolor = #cccccc)
        table.cell(monthly_table, 12, 0, "Dec",  bgcolor = #cccccc)
        table.cell(monthly_table, 13, 0, "Year", bgcolor = #999999)


        for yi = 0 to array.size(year_pnl) - 1
            table.cell(monthly_table, 0,  yi + 1, str.tostring(year(array.get(year_time, yi))), bgcolor = #cccccc)

            y_color = array.get(year_pnl, yi) > 0 ? color.new(color.teal, transp = 40) : color.new(color.gray, transp = 40)
            table.cell(monthly_table, 13, yi + 1, str.tostring(math.round(array.get(year_pnl, yi) * 100, prec)), bgcolor = y_color, text_color=color.new(color.white, 0))

        for mi = 0 to array.size(month_time) - 1
            m_row   = year(array.get(month_time, mi))  - year(array.get(year_time, 0)) + 1
            m_col   = month(array.get(month_time, mi))
            m_color = array.get(month_pnl, mi) > 0 ? color.new(color.teal, transp = 40) : color.new(color.gray, transp = 40)

            table.cell(monthly_table, m_col, m_row, str.tostring(math.round(array.get(month_pnl, mi) * 100, prec)), bgcolor = m_color, text_color=color.new(color.white, 0))


finandy_signal_name = input.string(title="Bot name", defval="", group="Alert settings")
finandy_secret = input.string(title="Finandy secret", defval="", group="Alert settings")

move_sl_after = movestoploss == 'TP-1' ? 1 :
                 movestoploss == 'TP-2' ? 2 :
                 movestoploss == 'TP-3' ? 3 :
                 na

var last_condition = ''

short_condition := short_condition and (last_condition == 'long' or last_condition == '') ? true : false
long_condition := long_condition and (last_condition == 'short' or last_condition == '') ? true : false

if(short_condition)
    last_condition := 'short'
    move_sl_after_str =  not na(move_sl_after) ? ',"slx":{"tpNum": ' + str.tostring(move_sl_after) + '}' : ''

    tp_str = ''

    for i = 1 to MAX_TP
        tp_str := tp_str + ',{"ofs": "' + str.tostring(short_profit_perc_setting * i) + '", "piece": "' + str.tostring(short_profit_qty) + '"}'

    tp_str := str.substring(tp_str, 1)

    alert_msg = '{"name": "' + finandy_signal_name + '", "secret": "' + finandy_secret + '", "side": "sell", "symbol": "' + syminfo.ticker + '",
                     "sl":{"ofs":"' + str.tostring(stoploss_setting) + '"},
                     "tp":{
                         "qty":"' + str.tostring(MAX_TP) + '",
                         "orders":['
                             + tp_str +
                         ']
                     },"close": {
                         "amountType": "openAmount",
                         "amount": ""                         
                     },
                     "positionSide": "both"'
                     + move_sl_after_str +
                 '}'

    alert(alert_msg,  alert.freq_once_per_bar)


if(long_condition)
    last_condition := 'long'
    move_sl_after_str =  not na(move_sl_after) ? ',"slx":{"tpNum": ' + str.tostring(move_sl_after) + '}' : ''

    tp_str = ''

    for i = 1 to MAX_TP
        tp_str := tp_str + ',{"ofs": "' + str.tostring(long_profit_perc_setting * i) + '", "piece": "' + str.tostring(long_profit_qty) + '"}'

    tp_str := str.substring(tp_str, 1)

    alert_msg = '{"name": "' + finandy_signal_name + '", "secret": "' + finandy_secret + '", "side": "buy", "symbol": "' + syminfo.ticker + '",
                     "sl":{"ofs":"' + str.tostring(stoploss_setting) + '"},
                     "tp":{
                         "qty":"' + str.tostring(MAX_TP) + '",
                         "orders":['
                             + tp_str +
                         ']
                     },"close": {
                         "amountType": "openAmount",
                         "amount": ""                         
                     },
                     "positionSide": "both"'
                     + move_sl_after_str +
                 '}'

    alert(alert_msg,  alert.freq_once_per_bar_close)

if(close_long_condition or close_short_condition)
    last_condition := ''
    alert_msg = '{"name": "' + finandy_signal_name + '", "secret": "' + finandy_secret + '", "symbol": "' + syminfo.ticker + '", "positionSide": "flat"}'
    alert(alert_msg,  alert.freq_once_per_bar_close)

if(partial_close_short_condition)
    alert_msg = '{"name": "' + finandy_signal_name + '", "secret": "' + finandy_secret + '", 
         "side": "buy", 
         "symbol": "' + syminfo.ticker + '", 
         "positionSide": "short", 
         "close": {"amountType": "posAmountPct", "amount": "' + str.tostring(bottom_qty) + '"}}'
    alert(alert_msg,  alert.freq_once_per_bar_close)


if(partial_close_long_condition)
    alert_msg = '{"name": "' + finandy_signal_name + '", "secret": "' + finandy_secret + '", 
         "side": "sell", 
         "symbol": "' + syminfo.ticker + '", 
         "positionSide": "long", 
         "close": {"amountType": "posAmountPct", "amount": "' + str.tostring(top_qty) + '"}}'
    alert(alert_msg,  alert.freq_once_per_bar_close)



//plotchar(long_condition, char='+', location=location.bottom, color=color.red, size=size.tiny)
//plotchar(strategy.position_size == 0, char='O', location=location.bottom, color=color.orange, size=size.tiny)
plotchar(long_condition, char='+', location=location.bottom, color=color.green, size=size.tiny)
plotchar(short_condition, char='-', location=location.bottom, color=color.red, size=size.tiny)
plotchar(partial_close_short_condition, char='B', location=location.bottom, color=color.orange, size=size.tiny)
plotchar(partial_close_long_condition, char='T', location=location.bottom, color=color.orange, size=size.tiny)
plotchar(close_long_condition or close_short_condition, char='C', location=location.bottom, color=color.orange, size=size.tiny)

