//@version=5
indicator(shorttitle="kane-BB", title="kane-Bollinger Bands", overlay=true, timeframe="", timeframe_gaps=true)
length = input.int(20, minval=1)
src = input(close, title="Source")
mult = input.float(2.0, minval=-50, maxval=50, title="StdDev")
basis = ta.sma(src, length)
dev = mult * ta.stdev(src, length)
upper = basis + dev
lower = basis - dev
offset = input.int(0, "Offset", minval = -500, maxval = 500)
plot(basis, "Basis", color=#1bcf0a, offset = offset)
p1 = plot(upper, "Upper", color=#2962FF, offset = offset)

bollinger_abv_percent = upper > upper[1] ? ((upper - upper[1])/((upper + upper[1])/2)) * 100 : na
p3 = plot(bollinger_abv_percent, "Percentage", color=#ff4229, offset = offset)