// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © atraderstoolbox

//@version=5
indicator("Lin Reg Simplified", overlay= true)

//Linear Regression Channel
linreg_length = input.int(title='Length ', defval=100, inline='2', maxval = 500, minval = 10, group='Regression Channel Settings')
linreg_deviation = input.float(title='Deviation ', defval=2, step=0.25, minval=0.5, maxval=5.00, inline='2', group='Regression Channel Settings')






linreg_bull = input.color(color.new(#27a69b, 70), title='Bull Color', inline='3', group='Regression Channel Settings')
linreg_mid = input.color(color.new(#000000, 0), title='Mid Color', inline='3', group='Regression Channel Settings')
linreg_bear = input.color(color.new(#b63632, 70), title='Bear Color', inline='3', group='Regression Channel Settings')


calculate_linreg(length, deviation) =>

    a = ta.wma(hlc3, length)
    b = ta.sma(hlc3, length)
    A = 4 * b - 3 * a
    B = 3 * a - 2 * b
    m = (A - B) / (length - 1)
    
    d = 0.00
    for i = 0 to length - 1 by 1
        l = B + m * i
        d += math.pow(hlc3[i] - l, 2)
        d

    linreg_1 = math.sqrt(d / (length - 1)) * deviation

    [A, m, B, linreg_1]
    
[tf1_A, tf1_m, tf1_B, tf1_linreg1] = calculate_linreg(linreg_length, linreg_deviation)

drawLinReg(color_input, A, m, B, k) =>
    line lr = line.new(bar_index - linreg_length + 1, A + k, bar_index + 50, -m*50 + (B + k), extend = extend.none, color = color_input, width = 1)
    line.delete(lr[1])
    
if true
    drawLinReg(linreg_mid, tf1_A, tf1_m, tf1_B, 0)
    drawLinReg(linreg_bear, tf1_A, tf1_m, tf1_B, tf1_linreg1)
    drawLinReg(linreg_bull, tf1_A, tf1_m, tf1_B, -tf1_linreg1)
