// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © atraderstoolbox

//@version=5
indicator(title="My Historical Volatility", shorttitle="HV", format=format.price, precision=2, timeframe="", timeframe_gaps=true)
length = input.int(10, minval=1)
annual = 365
per = timeframe.isintraday or timeframe.isdaily and timeframe.multiplier == 1 ? 1 : 7
hv = 100 * ta.stdev(math.log(close / close[1]), length) * math.sqrt(annual / per)
plot(hv, "HV", color=#2962FF)

[middle, upper, lower] = ta.bb(hv, 200, 1.0)
plot(middle, color=color.yellow)
plot(upper, color=color.yellow)
plot(lower, color=color.yellow)

bgcolor(hv >= upper ? color.new(color.yellow,90) : na)