// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © atraderstoolbox

//@version=4
study("My script")
plot(close)


// ————— Function returning a string representation of a numeric `_val` using a special `_fmt` string allowing all strings to be of the same width, to help align columns of values.
f_tostringPad(_val, _fmt) =>
    // float  _val: string to separate.
    // string _fmt: formatting string similar to those used in the `tostring()` format string, with "?" used to indicate padding, 
    //              e.g., "??0.00" to ensure that numbers always contain three characters left of the decimal point.
    //              WARNING: A minus sign MUST begin the format ("-??0.00") if negative values are to be handled, otherwise negative values will have no minus sign.

    // Character used to pad numbers: Unicode figure space (U+2007).
    var string FIGURE_SPACE = " "
    // Character used to pad minus signs: Unicode punctuation space (U+2008).
    var string PUNCTUATION_SPACE = " "
    // Preliminary conversion of the value to a string.
    string _formattedVal = tostring(_val, _fmt)
    // Remove minus sign from format string.
    _formattedVal := str.replace_all(_formattedVal, "-", "")
    // Split value and format string into characters.
    string[] _chars    = str.split(_formattedVal, "")
    string[] _charsFmt = str.split(_fmt, "")
    
    // Detect if we need to handle negative values, and if so, remove the minus sign from format.
    bool _handleNegs = array.get(_charsFmt, 0) == "-"
    if _handleNegs
        array.shift(_charsFmt)

    // Detect if value or format string are without a decimal point and if so, add a temporary one for our logic, which we'll remove later.
    int _pointPos    = array.indexof(_chars, ".")
    int _pointPosFmt = array.indexof(_charsFmt, ".")
    bool _noPoint    = _pointPos == -1
    bool _noPointFmt = _pointPosFmt == -1
    if _noPoint
        array.push(_chars, ".")
        _pointPos := array.indexof(_chars, ".")
    if _noPointFmt
        array.push(_charsFmt, ".")
        _pointPosFmt := array.indexof(_charsFmt, ".")

    // Remove extra instances of "?" in front of value.
    _extraChars = _pointPos - _pointPosFmt
    if _extraChars > 0
        for _i = 0 to _extraChars - 1
            array.shift(_chars)
    // Add minus sign or space if needed.
    if _handleNegs
        // Format accounts for negative values; insert minus sign or space.
        array.unshift(_chars, (_val < 0 ? "-" : PUNCTUATION_SPACE))
    // Remove temporary decimal point if needed.
    if _noPointFmt or _noPoint
        array.pop(_chars)
    // Rejoin our array and replace the "?" chars left in our result with figure space padding.
    string _return = array.join(_chars, "")
    _return := str.replace_all(_return, "?", FIGURE_SPACE)