//@version=5
strategy(title='Range Filter', overlay=true)




src = input(defval=close, title='Source')

// Sampling Period
// Settings for 5min chart, BTCUSDC. For Other coin, change the paremeters

per = input.int(defval=50, minval=1, title='Sampling Period')

// Range Multiplier

mult = input.float(defval=3.0, minval=0.1, title='Range Multiplier')

// Smooth Average Range

smoothrng(x, t, m) =>
    wper = t * 2 - 1
    avrng = ta.ema(math.abs(x - x[1]), t)
    smoothrng = ta.ema(avrng, wper) * m
    smoothrng
smrng = smoothrng(src, per, mult)

// Range Filter

rngfilt(x, r) =>
    rngfilt = x
    rngfilt := x > nz(rngfilt[1]) ? x - r < nz(rngfilt[1]) ? nz(rngfilt[1]) : x - r : x + r > nz(rngfilt[1]) ? nz(rngfilt[1]) : x + r
    rngfilt
filt = rngfilt(src, smrng)

// Filter Direction

upward = 0.0
upward := filt > filt[1] ? nz(upward[1]) + 1 : filt < filt[1] ? 0 : nz(upward[1])
downward = 0.0
downward := filt < filt[1] ? nz(downward[1]) + 1 : filt > filt[1] ? 0 : nz(downward[1])

// Target Bands

hband = filt + smrng
lband = filt - smrng

// Colors

filtcolor = upward > 0 ? color.lime : downward > 0 ? color.red : color.orange
barcolor = src > filt and src > src[1] and upward > 0 ? color.lime : src > filt and src < src[1] and upward > 0 ? color.green : src < filt and src < src[1] and downward > 0 ? color.red : src < filt and src > src[1] and downward > 0 ? color.maroon : color.orange

filtplot = plot(filt, color=filtcolor, linewidth=3, title='Range Filter')

// Target

hbandplot = plot(hband, color=color.new(color.aqua, 100), title='High Target')
lbandplot = plot(lband, color=color.new(color.fuchsia, 100), title='Low Target')

// Fills

fill(hbandplot, filtplot, color=color.new(color.aqua, 90), title='High Target Range')
fill(lbandplot, filtplot, color=color.new(color.fuchsia, 90), title='Low Target Range')

var ltp = 0.0
var lsl = 0.0
var stp = 0.0
var ssl = 0.0



long = upward and not upward[1]
short = downward and not downward[1]

longEntryMessage = input.text_area("", title="Long entry message", group="Alert messages", tooltip="Please use the Following message in Alert Message box while creating alert to pass these messages through webhook \n\n {{strategy.order.alert_message}}")
longExitMessage = input.text_area("", title="Long exit message", group="Alert messages")
shortEntryMessage = input.text_area("", title="Short entry message", group="Alert messages")
shortExitMessage = input.text_area("", title="Short exit message", group="Alert messages")

sl = input.int(5, 'Stop Loss %', group='SL/TP') / 100
tp = input.int(10, 'Take Profit %', group='SL/TP') / 100

use_tsl = input(true, "Use Trailing SL", group="SL")
trailing_sl = 0.0


if long
    strategy.entry('Long', strategy.long, alert_message = longEntryMessage)
if short
    strategy.entry('Short', strategy.short, alert_message = shortEntryMessage)


var float sl_val = na
if long and strategy.position_size<=0
    lsl := close * (1 - sl)
    ltp := close * (1 + tp)
    sl_val:=close-lsl
if short and strategy.position_size>=0
    ssl := close * (1 + sl)
    stp := close * (1 - tp)
    sl_val:= ssl-close 
// if close_signal
//     strategy.close("Long", alert_message = longExitMessage)
//     strategy.close('Short', alert_message = shortExitMessage)


p0 = plot(strategy.position_size != 0 ? strategy.position_avg_price : na, style=plot.style_linebr, title='Entry')
p1 = plot(strategy.position_size > 0 ? lsl : na, style=plot.style_linebr, color=color.new(color.red, 0), linewidth=1, title='Long SL')
p2 = plot(strategy.position_size < 0 ? ssl : na, style=plot.style_linebr, color=color.new(color.red, 0), linewidth=1, title='Short SL')
p3 = plot(strategy.position_size > 0 ? ltp : na, style=plot.style_linebr, color=color.new(color.green, 0), linewidth=1, title='Long Take Profit')
p4 = plot(strategy.position_size < 0 ? stp : na, style=plot.style_linebr, color=color.new(color.green, 0), linewidth=1, title='Short Take Profit')

fill(p0, p3, color=color.new(color.green, 80))
fill(p0, p1, color=color.new(color.red, 80))

fill(p0, p4, color=color.new(color.green, 80))
fill(p0, p2, color=color.new(color.red, 80))




long_signal =  strategy.position_size<=0 and long// and (use_exit ? maShortTermXtrender > maShortTermXtrender[1]: true)
short_signal = strategy.position_size>=0 and short// and (use_exit ? maShortTermXtrender < maShortTermXtrender[1]: true)

trailing_sl := short_signal ? ssl : long_signal ? lsl : strategy.position_size>0 ? math.max(low - sl_val, nz(trailing_sl[1])) : strategy.position_size<0? math.min(high + sl_val, nz(trailing_sl[1])) : nz(trailing_sl[1])
// plot(strategy.position_size!=0 and use_tsl? trailing_sl : na, linewidth=2, color=strategy.position_size<0 ? color.red : strategy.position_size>0 ? color.green : color.new(color.white, 100) , style= plot.style_linebr)



strategy.exit('Long Exit', from_entry='Long', limit=ltp, stop=(use_tsl ?trailing_sl: lsl) , alert_message = longExitMessage)
strategy.exit('Short Exit', from_entry='Short', limit=stp, stop=(use_tsl ?trailing_sl:ssl) , alert_message = shortExitMessage)
