//@version=5
indicator(title= "RVOL++")

import TradingView/ta/7
import TradingView/RelativeValue/2 as rv

// assertions
var cumVol = 0.
cumVol += nz(volume)
if barstate.islast
    if cumVol == 0
        runtime.error("The data vendor doesn't provide volume data for this symbol.")

    if timeframe.in_seconds() >= timeframe.in_seconds("60")
        runtime.error("RVOL is meant to be used on small timeframes")


// inputs
rvol_use_5min = input.bool(true, title ='Use 5min data', group = 'RVOL Settings')
rvol_type = input.string("Two Session", title = 'RVOL Type', options = ['Two Session', 'Daily'], group = 'RVOL Settings')
rvol_days = input.int(20, title = 'RVOL Days', group = 'RVOL Settings', minval=5, maxval=50)
rvol_time1 = input.session('0930-1700', title='RVOL Time (EST)', group = 'RVOL Settings')
plot_style = input.string("Default", title = "Plot Style", options = ['Default', 'Regular Volume'])

is_rvol_time1 = time == time(timeframe.period, str.format('{0}:1234567', rvol_time1), 'America/New_York')

// functions
f_calculate_rvol(sess_type) =>
    is_rvol = time == time(timeframe.period, str.format('{0}:1234567', rvol_time1), 'America/New_York')
    bool anchor =  rvol_type != "Two Session" ? timeframe.change("1D") : sess_type == 1 ? (is_rvol and not is_rvol[1]) : (not is_rvol and is_rvol[1])
    bool useCumulative = true
    float currVol = rv.calcCumulativeSeries(volume, anchor, useCumulative)
    float pastVol  = rv.averageAtTime(volume, rvol_days, anchor, useCumulative)
    float volRatio = math.round(currVol / pastVol * 100,0)
    volRatio[1]


f_5minute_data() =>
    [rvol_rth, rvol_on] =
         request.security("", "5", [
         f_calculate_rvol(1),
         f_calculate_rvol(0)
         ]
         )

f_regular_data() =>
    rvol_rth = f_calculate_rvol(1)
    rvol_on = f_calculate_rvol(0)

    [rvol_rth, rvol_on]

// calculate
var float rvol_value = na
var float rvol_rth = na
var float rvol_on = na

if rvol_use_5min
    [rvol_rth_calc, rvol_calc_on] = f_5minute_data()
    rvol_rth := rvol_rth_calc
    rvol_on := rvol_calc_on
else
    [rvol_rth_calc, rvol_calc_on] = f_regular_data()
    rvol_rth := rvol_rth_calc
    rvol_on := rvol_calc_on



if rvol_type == "Two Session"
    rvol_value := is_rvol_time1 ? rvol_rth : rvol_on
else
    rvol_value := rvol_rth




rvol_hist_color = color.from_gradient(rvol_value, ta.lowest(rvol_value[1], 2000), ta.highest(rvol_value[1], 2000), chart.bg_color, chart.fg_color)
rvol_zone0 = color.from_gradient(rvol_value, 50, 80, color.rgb(86, 0, 0), color.rgb(235, 213, 18, 20))
rvol_zone1 = color.from_gradient(rvol_value, 80, 120, color.rgb(0, 56, 226), color.rgb(13, 155, 231))
rvol_zone2 = color.from_gradient(rvol_value, 120, 150, color.rgb(13, 231, 231), color.rgb(0, 255, 94))
rvol_zone3 = color.from_gradient(rvol_value, 150, 250, color.rgb(30, 255, 0), color.rgb(179, 255, 0))

rvol_color = 
 rvol_value > 150 ? rvol_zone3 :
 rvol_value > 120 ? rvol_zone2 :
 rvol_value > 80 ? rvol_zone1:
 rvol_zone0


// plotting
show_rvol_plot = plot_style == "Default"
show_volume_plot = plot_style == "Regular Volume"
bgcolor(not is_rvol_time1 ? color.new(#5A6471,82) : na)
plot(show_rvol_plot ? rvol_value : na, title = "RVOL Hist", style = plot.style_areabr, color = rvol_color, histbase = 80, display = show_rvol_plot ? display.all : display.none)
plot(show_rvol_plot ? rvol_value : na, title = 'RVOL Outline',color = color.black, style = plot.style_steplinebr, linewidth = 5, display = show_rvol_plot ? display.all : display.none)
plot(show_rvol_plot ? rvol_value : na, title = 'RVOL',color = rvol_color, style = plot.style_steplinebr, linewidth = 2, display = show_rvol_plot ? display.all : display.none)

plot(show_volume_plot ? volume : na, title = 'Volume', color=chart.fg_color, style= plot.style_columns, display = show_volume_plot ? display.all : display.none)
plot(show_volume_plot ? 0 : na, title = 'RVOL Dots', color=rvol_color, style= plot.style_line, linewidth=3, display = show_volume_plot ? display.all : display.none)

rvol_label = table.new(position = position.middle_right, columns = 1, rows = 1)
if barstate.islast
    table.cell(rvol_label, 0,0, text = "RVOL=" + str.tostring(rvol_value[1]), text_color = chart.bg_color, bgcolor = color.new(#5A6471, 0 ))

