// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © atraderstoolbox

//@version=5
indicator("Supersaiyan Strategy", overlay = true)


// trade settings
a_plus = input.bool(true, title = 'A+', group = 'Trade Settings', inline = '1')
b_plus = input.bool(true, title = 'B+', group = 'Trade Settings', inline = '2')
b = input.bool(true, title = 'B', group = 'Trade Settings', inline = '3')
b_minus = input.bool(true, title = 'B-', group = 'Trade Settings', inline = '4')
c = input.bool(true, title = 'C', group = 'Trade Settings', inline = '5')






// macd settings
macd_fastlength = input.int(12, title = 'MACD Fast', group = 'MACD Settings', inline = '1')
macd_slowlength = input.int(26, title = 'MACD Slow', group = 'MACD Settings', inline = '2')
macd_length = input.int(9, title = 'MACD Length', group = 'MACD Settings', inline = '3')

// ma cross settings
ma_length1 = input.int(5, title = 'EMA Cross Eachother Length 1', group = 'MA Settings', inline = '1')
ma_length2 = input.int(8, title = 'EMA Cross Eachother Length 2', group = 'MA Settings', inline = '2')
ma_length3 = input.int(9, title = 'Close Cross EMA Length', group = 'MA Settings', inline = '3')



























// calculations
[macdLine, signalLine, histLine] = ta.macd(close, macd_fastlength, macd_slowlength, macd_length)
crossma1 = ta.ema(close, ma_length1)
crossma2 = ta.ema(close, ma_length2)
ma3 = ta.ema(close, ma_length3)
vwap = ta.vwap




// plots
plot(crossma1, title = 'EMA Crossing 1', color = color.orange)
plot(crossma2, title = 'EMA Crossing 2', color = color.yellow)
plot(ma3, title = 'EMA', color = color.fuchsia)
plot(vwap, title = 'VWAP', color = color.blue)