//@version=5
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/

// True Momentum Oscillator
// by SparkyFlary

indicator(title='True Momentum Oscillator', overlay=false, timeframe = '')

length = input(12, title='Length')
calcLength = input(3, title='Calc length')
smoothLength = input(2, title='Smooth length')
lengthType = input.string('EMA', title='Length moving average type', options=['EMA', 'SMA', 'RMA'])
calcLengthType = input.string('EMA', title='Calc length moving average type', options=['EMA', 'SMA', 'RMA'])
smoothLengthType = input.string('EMA', title='Smooth length moving average type', options=['EMA', 'SMA', 'RMA'])

//function for choosing moving averages
f_ma(type, src, len) =>
    float result = 0
    if type == 'EMA'
        result := ta.ema(src, len)
        result
    if type == 'SMA'
        result := ta.sma(src, len)
        result
    if type == 'RMA'
        result := ta.rma(src, len)
        result
    result

o = open
c = close
s = 0
for i = 0 to length by 1
    s += (c > o[i] ? 1 : c < o[i] ? -1 : 0)
    s
data = s

MA = f_ma(lengthType, data, calcLength)
Main = f_ma(calcLengthType, MA, smoothLength)
Signal = f_ma(smoothLengthType, Main, smoothLength)

ob = hline(math.round(length * .7), title='overbought cutoff line', color=color.gray, linestyle=hline.style_solid)
os = hline(-math.round(length * .7), title='oversold cutoff line', color=color.gray, linestyle=hline.style_solid)
upper = hline(length, title='upper line', color=color.red, linestyle=hline.style_solid)
lower = hline(-length, title='lower line', color=color.green, linestyle=hline.style_solid)
zero = hline(0, title='zero line', color=color.gray, linestyle=hline.style_solid)

mainPlot = plot(Main, title='main line', color=Main > Signal ? color.green : color.red, linewidth=2)
signalPlot = plot(Signal, title='signal line', color=Main > Signal ? color.green : color.red)
crossPlot = plot(ta.cross(Main, Signal) ? Main : na, title='crossover dot', color=Main > Signal ? color.green : color.red, style=plot.style_circles, linewidth=3)

fill(mainPlot, signalPlot, title='main and signal area', color=Main > Signal ? color.green : color.red, transp=90)
fill(ob, upper, title='overbought zone', color=color.new(color.red, 90))
fill(os, lower, title='oversold zone', color=color.new(color.green, 90))

