// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © atraderstoolbox

//@version=5
indicator("U.S. Futures Price Limits (Deprecated)", overlay = true)


//
// GLOBAL INPUTS
//
show_labels = input.bool(true, title = "Show Labels", group = 'Global Settings', inline = '1')
labels_spacing = input.int(5, title = '  |  Spacing', minval = 1, maxval = 50, group = 'Global Settings', inline = '1')
settlement_color = input.color(color.new(color.white, 20), title = 'Settlement Color', group = 'Global Settings', inline = '2')
limitup_color = input.color(color.new(color.yellow, 20), title = 'Limit Up Color', group = 'Global Settings', inline = '3')
limitdown_color = input.color(color.new(color.yellow, 20), title = 'Limit Down Color', group = 'Global Settings', inline = '4')


// 
// EQUITY INDEXES INPUTS
// 

//ES or //MES
MES_ES_pct1 = input.float(7.00, title = ' ', group = 'ES & MES Limits', inline = '1')
MES_ES_pct2 = input.float(13.00, title = ' ', group = 'ES & MES Limits', inline = '1')
MES_ES_pct3 = input.float(20.00, title = ' ', group = 'ES & MES Limits', inline = '1')

//NQ or //MNQ
MNQ_NQ_pct1 = input.float(7.00, title = ' ', group = 'NQ & MNQ Limits', inline = '1')
MNQ_NQ_pct2 = input.float(13.00, title = ' ', group = 'NQ & MNQ Limits', inline = '1')
MNQ_NQ_pct3 = input.float(20.00, title = ' ', group = 'NQ & MNQ Limits', inline = '1')

//YM or //MYM
MYM_YM_pct1 = input.float(7.00, title = ' ', group = 'YM & MYM Limits', inline = '1')
MYM_YM_pct2 = input.float(13.00, title = ' ', group = 'YM & MYM Limits', inline = '1')
MYM_YM_pct3 = input.float(20.00, title = ' ', group = 'YM & MYM Limits', inline = '1')

//RTY or //M2K
M2K_RTY_pct1 = input.float(7.00, title = ' ', group = 'RTY & M2K Limits', inline = '1')
M2K_RTY_pct2 = input.float(13.00, title = ' ', group = 'RTY & M2K Limits', inline = '1')
M2K_RTY_pct3 = input.float(20.00, title = ' ', group = 'RTY & M2K Limits', inline = '1')









//MAPPING SYMBOLS & PERCENTS
var float limit_up_1 = 0.00
var float limit_up_2 = 0.00
var float limit_up_3 = 0.00

var float limit_down_1 = 0.00
var float limit_down_2 = 0.00
var float limit_down_3 = 0.00

settlement = request.security(syminfo.ticker, "D", close[1], barmerge.gaps_off, barmerge.lookahead_on)
    
//EQUITY INDEXES MAPPING SYMBOLS
if syminfo.root == 'ES' or syminfo.root == 'MES'
    limit_up_1 := math.round_to_mintick(settlement + (settlement * MES_ES_pct1))
    limit_up_2 := math.round_to_mintick(settlement + (settlement * MES_ES_pct2))
    limit_up_3 := math.round_to_mintick(settlement + (settlement * MES_ES_pct3))
    limit_down_1 := math.round_to_mintick(settlement - (settlement * MES_ES_pct1))
    limit_down_2 := math.round_to_mintick(settlement - (settlement * MES_ES_pct2))
    limit_down_3 := math.round_to_mintick(settlement - (settlement * MES_ES_pct3))
    
else if syminfo.root == 'NQ' or syminfo.root == 'MNQ'
    limit_up_1 := math.round_to_mintick(settlement + (settlement * MNQ_NQ_pct1))
    limit_up_2 := math.round_to_mintick(settlement + (settlement * MNQ_NQ_pct2))
    limit_up_3 := math.round_to_mintick(settlement + (settlement * MNQ_NQ_pct3))
    limit_down_1 := math.round_to_mintick(settlement - (settlement * MNQ_NQ_pct1))
    limit_down_2 := math.round_to_mintick(settlement - (settlement * MNQ_NQ_pct2))
    limit_down_3 := math.round_to_mintick(settlement - (settlement * MNQ_NQ_pct3))

else if syminfo.root == 'YM' or syminfo.root == 'MYM'
    limit_up_1 := math.round_to_mintick(settlement + (settlement * MYM_YM_pct1))
    limit_up_2 := math.round_to_mintick(settlement + (settlement * MYM_YM_pct2))
    limit_up_3 := math.round_to_mintick(settlement + (settlement * MYM_YM_pct3))
    limit_down_1 := math.round_to_mintick(settlement - (settlement * MYM_YM_pct1))
    limit_down_2 := math.round_to_mintick(settlement - (settlement * MYM_YM_pct2))
    limit_down_3 := math.round_to_mintick(settlement - (settlement * MYM_YM_pct3))

else if syminfo.root == 'RTY' or syminfo.root == 'M2K'
    limit_up_1 := math.round_to_mintick(settlement + (settlement * M2K_RTY_pct1))
    limit_up_2 := math.round_to_mintick(settlement + (settlement * M2K_RTY_pct2))
    limit_up_3 := math.round_to_mintick(settlement + (settlement * M2K_RTY_pct3))
    limit_down_1 := math.round_to_mintick(settlement - (settlement * M2K_RTY_pct1))
    limit_down_2 := math.round_to_mintick(settlement - (settlement * M2K_RTY_pct2))
    limit_down_3 := math.round_to_mintick(settlement - (settlement * M2K_RTY_pct3))


else
    limit_up_1 := na
    limit_up_2 := na
    limit_up_3 := na
    
    limit_down_1 := na
    limit_down_2 := na
    limit_down_3 := na




day_change = ta.change(time("D"))
plot(settlement, color = day_change ? na : settlement_color, title = "Settlement", editable = false)





plot(limit_up_1, color = day_change ? na : limitup_color, title = "Limit Up 1", editable = false)
plot(limit_up_2, color = day_change ? na : limitup_color, title = "Limit Up 2", editable = false)
plot(limit_up_3, color = day_change ? na : limitup_color, title = "Limit Up 3", editable = false)

plot(limit_down_1, color = day_change ? na : limitdown_color, title = "Limit Down 1", editable = false)
plot(limit_down_2, color = day_change ? na : limitdown_color, title = "Limit Down 2", editable = false)
plot(limit_down_3, color = day_change ? na : limitdown_color, title = "Limit Down 3", editable = false)

if barstate.islast
    if show_labels
        // settlement_label = label.new(bar_index + 1, settlement, text = 'Settlement: ' + str.tostring(settlement), style = label.style_label_left, textalign = text.align_right, size = size.small, color = settlement_color, textcolor = color.black)
        settlement_label = label.new(bar_index + labels_spacing, settlement, text = 'Settlement: ' + str.tostring(syminfo.root), style = label.style_label_left, textalign = text.align_right, size = size.small, color = settlement_color, textcolor = color.black)
        
        limitup1_label = label.new(bar_index + labels_spacing, limit_up_1, text = 'Limit Up 1: ' + str.tostring(limit_up_1), style = label.style_label_left, textalign = text.align_right, size = size.small, color = limitup_color, textcolor = color.black)       
        limitup2_label = label.new(bar_index + labels_spacing, limit_up_2, text = 'Limit Up 2: ' + str.tostring(limit_up_2), style = label.style_label_left, textalign = text.align_right, size = size.small, color = limitup_color, textcolor = color.black)       
        limitup3_label = label.new(bar_index + labels_spacing, limit_up_3, text = 'Limit Up 3: ' + str.tostring(limit_up_3), style = label.style_label_left, textalign = text.align_right, size = size.small, color = limitup_color, textcolor = color.black)       

        limitdown1_label = label.new(bar_index + labels_spacing, limit_down_1, text = 'Limit Down 1: ' + str.tostring(limit_down_1), style = label.style_label_left, textalign = text.align_right, size = size.small, color = limitdown_color, textcolor = color.black)       
        limitdown2_label = label.new(bar_index + labels_spacing, limit_down_2, text = 'Limit Down 2: ' + str.tostring(limit_down_2), style = label.style_label_left, textalign = text.align_right, size = size.small, color = limitdown_color, textcolor = color.black)       
        limitdown3_label = label.new(bar_index + labels_spacing, limit_down_3, text = 'Limit Down 3: ' + str.tostring(limit_down_3), style = label.style_label_left, textalign = text.align_right, size = size.small, color = limitdown_color, textcolor = color.black)  
        
        if not na(settlement_label[1])
            label.delete(settlement_label[1])

            label.delete(limitup1_label[1])
            label.delete(limitup2_label[1])
            label.delete(limitup3_label[1])

            label.delete(limitdown1_label[1])
            label.delete(limitdown2_label[1])
            label.delete(limitdown3_label[1])
            
            
            
            
            