// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © GoodGains

//@version=5
indicator("Volume Spike Candles", overlay = false)


// inputs
calcTime = input.session('0940-1530', title = 'Allowed Alert Time', group = 'Calculate')
length = input.int(100, title="Lookback", group = 'Calculate')
mult = input.float(4.0, title="Multiplier", group = 'Calculate')

only_alerts = input.bool(false, title = 'Only Color Candles During Alert Time', group = 'Other')
show_yellow = input.bool(true, title = 'Show Neutral Volume Spike', group = 'Other')

// functions
f_adjust_brightness(c, factor) => 
    r = na(color.r(c)) ? 0 : color.r(c)
    g = na(color.g(c)) ? 0 : color.g(c)
    b = na(color.b(c)) ? 0 : color.b(c)

    r := math.min(math.max(r * factor, 0), 255)
    g := math.min(math.max(g * factor, 0), 255)
    b := math.min(math.max(b * factor, 0), 255)

    return_color = color.rgb(r, g, b)

//keltner price bands
f_kc(src, length, mult) =>
    float basis = ta.ema(src, length)
    float span = (high - low)
    float rangeEma = ta.ema(span, length/2)
    [basis, basis + rangeEma * mult, basis - rangeEma * mult]

[middle, upper, lower] = f_kc(hl2, length, mult)


// volume extreme
var bool volumeSpike = na
var bool topVolumeExtreme = na
var bool botVolumeExtreme = na
var bool netVolumeExtreme = na

var int lastColor = na

isCalcTime = time == time(timeframe.period, str.format('{0}:1234567', calcTime), 'America/New_York')

volumeSMA = ta.sma(volume, length)
volumeSTD = ta.stdev(volume, length)
upperBound = volumeSMA + (volumeSTD * mult)
volumeSpike := volume > upperBound

topVolumeExtreme := volumeSpike and high >= upper[1]
botVolumeExtreme := volumeSpike and low <= lower[1]
netVolumeExtreme := volumeSpike and not topVolumeExtreme and not botVolumeExtreme
lastColor := topVolumeExtreme ? 1 : botVolumeExtreme ? -1 : netVolumeExtreme ? 0 : lastColor[1]


// plot
regularColor = color.rgb(122,134,150)
candleColor = only_alerts and not isCalcTime ? color.new(regularColor, 25)
 : topVolumeExtreme ? color.green
 : botVolumeExtreme ? color.red 
 : volumeSpike and show_yellow ? color.yellow 
 : color.new(regularColor, 25)

barcolor(candleColor)
plot(volume, title = "Volume", color = candleColor, style = plot.style_columns)
plotcandle(open, high, low, close, title='Custom Candle', force_overlay = true, color = candleColor,
 wickcolor=(volumeSpike ? f_adjust_brightness(candleColor, .65) : color.new(regularColor, 25)), 
 bordercolor=(volumeSpike ? f_adjust_brightness(candleColor, .65) : color.new(regularColor, 25)))
