// © goodgains
//@version=5
strategy(title='vwap-test 11-30-22', overlay=true, calc_on_every_tick=true, max_bars_back=300, default_qty_value = 100000, default_qty_type = strategy.cash)

// @keywords: vwap-strategy, vwap-crossover, opening-session, profit-target, stop-loss, trailing-stop, ott-rising, day-trade-limit, volume-filter, sma-filter, fibonacci-levels, entry-exit-session, kane-bb-trail, calc-every-tick, long-only-trades, trade-spacing, vwap-entry, strategy-test, session-window, position-management

//BUTTONS /////////////////////////////////////////////////////////////////////////////////
usaSma= input.bool(false,title='Close above/below SMA3 - entry condition')
buy_delay =  input.bool(false, title='$ Entry delayed one bar')
usa_limit_trades = input.bool(false, title='$ Limit # of day trades')
color_trades = input.bool(false, title='$ Highlight entry trades')
delay_next_trade_button = input.bool(true, title='Space btw trades - entry trades')
vwap_button = input.bool(true, title='$ must crs thru VWAP - entry trades ------ THE ONE')
ott_rising_button = input.bool(true, title='$ ott/rising - entry trades ---- THE ONE')

//TAKE PROFIT-STOP LOSS-TRAIL/////////////////////////////////////////////////////////////////////////////////////
entry_use_TradingHours = input.bool(true, title = " ", tooltip = "This is ignored if the chart timeframe is greater than or equal to the daily timeframe.", group = "Additional Trade Settings",inline = '1')
entry_trading_time = input.session("0930-0950", title = "Entry Trading Time", tooltip = "This uses Eastern Time Zone or U.S. NY Market Hours.", group = "Additional Trade Settings",inline = '1')
entry_trading_hours_cond = not entry_use_TradingHours or time("",entry_trading_time, "America/New_York")

exit_use_TradingHours = input.bool(true, title = " ", tooltip = "This is ignored if the chart timeframe is greater than or equal to the daily timeframe.", group = "Additional Trade Settings",inline = '2')
exit_trading_time = input.session("0932-1545", title = "Exit Trading Time", tooltip = "This uses Eastern Time Zone or U.S. NY Market Hours.", group = "Additional Trade Settings",inline = '2')
exit_trading_hours_cond = not exit_use_TradingHours or time("",exit_trading_time, "America/New_York")

long_trades = input.bool(true, title = "Long Trades", tooltip = "Do we want to take long trades?" , group = "Additional Trade Settings",inline = '3')

use_profit_target = input.bool(true, title = "Profit Target", tooltip = "Do we want to use a profit target?" , group = "Additional Trade Settings",inline = '4')
pt_amount = input.float(5.00, minval = 0.00, maxval = 99.0, step = 0.25,  title = " ", group = "Additional Trade Settings", inline = '4')

use_stop = input.bool(true, title = "Stop", tooltip = "Do we want to use a hard stop loss?" , group = "Additional Trade Settings",inline = '5')
stop_amount = input.float(1.50, minval = 0.00, maxval = 99.0, step = 0.25, title = " ", group = "Additional Trade Settings", inline = '5')

use_trailing_stop = input.bool(false, title = "Kane-BB Trailing Stop", tooltip = "Do we want to use a trailing stop loss?" , group = "Additional Trade Settings",inline = '6')
// trailing_stop_amount = input.float(2.50, minval = 0.00, maxval = 99.0, step = 0.25, title = " ", group = "Additional Trade Settings", inline = '6')
trailing_stop_amount = 2.5

ts_length = input.int(20, minval=1, title = 'TS Length', group = "Additional Trade Settings",inline = '7')
ts_src = input(close, title="Source", title = 'Source', group = "Additional Trade Settings",inline = '7')
ts_mult = input.float(2.0, minval=-50, maxval=50, title="Stdev", group = "Additional Trade Settings",inline = '7')

//Candle_Close////////////////////////////////////////////////////////////////////
candle_close = ta.highest(close,1)
candle_open = ta.lowest(open,1)
candle_high = ta.highest(high,1)
candle_low = ta.lowest(low,1)

// Volume//////////////////////////////////////////////////////////////////////
volume_min = input.int(100000, minval = 50000, title = 'Minimum Volume', group = 'Trade Settings', inline = '5')

volume_buy = volume >= volume_min
volume_sell = volume >= volume_min

// Relative Strength Index - RSI/////////////////////////////////////////////////////////
ma(source, length, type) =>
    switch type
        "SMA" => ta.sma(source, length)
        "Bollinger Bands" => ta.sma(source, length)
        "EMA" => ta.ema(source, length)
        "SMMA (RMA)" => ta.rma(source, length)
        "WMA" => ta.wma(source, length)
        "VWMA" => ta.vwma(source, length)

rsiLengthInput = input.int(14, minval=1, title="RSI Length", group="RSI Settings")
rsiSourceInput = input.source(close, "Source", group="RSI Settings")
maTypeInput = input.string("SMA", title="MA Type", options=["SMA", "Bollinger Bands", "EMA", "SMMA (RMA)", "WMA", "VWMA"], group="RSI Settings")
maLengthInput = input.int(14, title="MA Length", group="RSI Settings")
bbMultInput = input.float(2.0, minval=0.001, maxval=50, title="BB StdDev", group="RSI Settings")

up = ta.rma(math.max(ta.change(rsiSourceInput), 0), rsiLengthInput)
down = ta.rma(-math.min(ta.change(rsiSourceInput), 0), rsiLengthInput)
rsi = down == 0 ? 100 : up == 0 ? 0 : 100 - (100 / (1 + up / down))
rsiMA = ma(rsi, maLengthInput, maTypeInput)
isBB = maTypeInput == "Bollinger Bands"

//RSI PERCENTAGE/////////////////////////////////////////////////////////////
rsi_abv_percent = rsi > rsiMA ? ((rsi - rsiMA)/((rsi + rsiMA)/2)) * 100 : na

//Optimized Trend Tracker Bands - OTT Bands///////////////////////////////////////////////////////
src = input(close, title='Source', group="OTT Settings")
length = input.int(2, 'OTT Moving Average Length', minval=1, group="OTT Settings")
percent = input.float(15, 'OTT Optimization Coeff', step=0.1, minval=0, group="OTT Settings")
X3 = input.float(0.1, 'OTT UPPER BAND Optimization Coeff', step=0.001, minval=0, group="OTT Settings")
X5 = input.float(0.077, 'OTT LOWER BAND Optimization Coeff', step=0.001, minval=0, group="OTT Settings")
showfibolines = input(title='Show OTT Bands Fibonacci Levels?', defval=false, group="OTT Settings")
showsupport = input(title='Show Support Line?', defval=false, group="OTT Settings")
highlight = input(title='Show OTT Support Line Color Changes?', defval=false, group="OTT Settings")
mav = input.string(title='Moving Average Type', defval='VAR', options=['SMA', 'EMA', 'WMA', 'TMA', 'VAR', 'WWMA', 'ZLEMA', 'TSF'], group="OTT Settings")
Var_Func(src, length) =>
    valpha = 2 / (length + 1)
    vud1 = src > src[1] ? src - src[1] : 0
    vdd1 = src < src[1] ? src[1] - src : 0
    vUD = math.sum(vud1, 9)
    vDD = math.sum(vdd1, 9)
    vCMO = nz((vUD - vDD) / (vUD + vDD))
    VAR = 0.0
    VAR := nz(valpha * math.abs(vCMO) * src) + (1 - valpha * math.abs(vCMO)) * nz(VAR[1])
    VAR
VAR = Var_Func(src, length)
Wwma_Func(src, length) =>
    wwalpha = 1 / length
    WWMA = 0.0
    WWMA := wwalpha * src + (1 - wwalpha) * nz(WWMA[1])
    WWMA
WWMA = Wwma_Func(src, length)
Zlema_Func(src, length) =>
    zxLag = length / 2 == math.round(length / 2) ? length / 2 : (length - 1) / 2
    zxEMAData = src + src - src[zxLag]
    ZLEMA = ta.ema(zxEMAData, length)
    ZLEMA
ZLEMA = Zlema_Func(src, length)
Tsf_Func(src, length) =>
    lrc = ta.linreg(src, length, 0)
    lrc1 = ta.linreg(src, length, 1)
    lrs = lrc - lrc1
    TSF = ta.linreg(src, length, 0) + lrs
    TSF
TSF = Tsf_Func(src, length)
getMA(src, length) =>
    ma = 0.0
    if mav == 'SMA'
        ma := ta.sma(src, length)
        ma

    if mav == 'EMA'
        ma := ta.ema(src, length)
        ma

    if mav == 'WMA'
        ma := ta.wma(src, length)
        ma

    if mav == 'TMA'
        ma := ta.sma(ta.sma(src, math.ceil(length / 2)), math.floor(length / 2) + 1)
        ma

    if mav == 'VAR'
        ma := VAR
        ma

    if mav == 'WWMA'
        ma := WWMA
        ma

    if mav == 'ZLEMA'
        ma := ZLEMA
        ma

    if mav == 'TSF'
        ma := TSF
        ma
    ma

MAvg = getMA(src, length)
fark = MAvg * percent * 0.01
longStop = MAvg - fark
longStopPrev = nz(longStop[1], longStop)
longStop := MAvg > longStopPrev ? math.max(longStop, longStopPrev) : longStop
shortStop = MAvg + fark
shortStopPrev = nz(shortStop[1], shortStop)
shortStop := MAvg < shortStopPrev ? math.min(shortStop, shortStopPrev) : shortStop
dir = 1
dir := nz(dir[1], dir)
dir := dir == -1 and MAvg > shortStopPrev ? 1 : dir == 1 and MAvg < longStopPrev ? -1 : dir
MT = dir == 1 ? longStop : shortStop
OTT = MAvg > MT ? MT * (200 + percent) / 200 : MT * (200 - percent) / 200
OTTC = highlight ? MAvg > MAvg[1] ? color.green : color.red : #0585E1
//OTTMAIN = plot(nz(OTT[2]), color=color.new(#B800D9, 0), linewidth=2, title='OTT')
//plot(showsupport ? MAvg : na, color=OTTC, linewidth=2, title='Support Line')
OTTUST = plot(nz(OTT[2]) * (1 + X3), color=color.new(#83c400, 0), linewidth=2, title='OTT UPPER')

// OTT BUY CONDITIONS////////////////////////////////////////////////////////////////////
ott_upper = nz(OTT[2]) * (1 + X3)
//plot(ott_upper, color=color.green)

//SMA and EMA CODE /////////////////////////////////////////////////////////
smaInput1 = input(9, title='SMA1', group = 'Indicator Settings', inline = '9')
smaInput2 = input(50, title='SMA2', group = 'Indicator Settings', inline = '10')
smaInput3 = input(180, title='SMA3', group = 'Indicator Settings', inline = '11')
emaInput1 = input(20, title='EMA1', group = 'Indicator Settings', inline = '12')
sma1 = ta.sma(close, smaInput1)
sma2 = ta.sma(close, smaInput2)
sma3 = ta.sma(close, smaInput3)
EMA1 = ta.ema(close, emaInput1)

sma3_buy = usaSma and long_trades ? close > sma3 : close

plot(sma1, color=color.new(color.purple, 0), title='SMA1')
plot(sma3, color=color.new(color.black, 0), title='SMA3')

// BOLLINGER BANDS /////////////////////////////////////////////////////////
length12 = input.int(20, minval=1, group="Bollinger Bands Settings")
src12 = input(close, title="Source", group="Bollinger Bands Settings")
mult = input.float(3.0, minval=-50, maxval=50, title="StdDev", group="Bollinger Bands Settings")
basis = ta.sma(src12, length12)
dev = mult * ta.stdev(src12, length12)
upper = basis + dev
lower = basis - dev
offset2 = input.int(0, "Offset", minval = -500, maxval = 500, group="Bollinger Bands Settings")
//plot(basis, "Basis", color=color.rgb(255, 109, 0), offset = offset2)
p1 = plot(upper, "Upper", color=#ff7f29, offset = offset2)
//p2 = plot(lower, "Lower", color=#2962FF, offset = offset2)
//fill(p1, title = "Background", color=color.rgb(33, 150, 243, 95))

bollinger_abv_percent = upper > upper[1] ? ((upper - upper[1])/((upper + upper[1])/2)) * 100 : na
//p2 = plot(bollinger_abv_percent, "Lower", color=#2962FF, offset = offset)

//Bar Index - 0 equal the 1st trade///////////////////////////////////////////
in_time_range = (time(timeframe.period, entry_trading_time))

//if in_time_range//////////////////////////////////////////////////////
one_day_trade = bar_index == 0

//Number of bars rising required for entry////////////////////////////////////////////////////
rising_bars = input(1, title='Rising bars for entry', group = 'Trade Settings', inline = '3')
bar_rising_buy = ta.rising(close, rising_bars)

// Create inputs////////////////////////////////////////////////////////////
session  = input.session("0400-1600", title="Session")
timeZone = input.string("GMT-4", title="Time Zone")

// first candle of the day//////////////////////////////////////////////////////
isNewDay = time("D",session) != time("D")[1]
bgcolor(isNewDay ? color.new(color.black, 50) : na)

//CLOSE ENTRY AFTER X AMOUNT OR BARS///////////////////////////////////////////////////////////
//close_bar_entry = bar_index - strategy.opentrades.entry_bar_index(strategy.opentrades - 1)
close_bar_entry = strategy.opentrades - strategy.opentrades[8] == 0

// BUY/SELL CONDITIONS//////////////////////////////////////////////////
Buy =  rsi > rsiMA
Sell =   rsi < rsiMA //or and exit_trading_hours_cond

//Delay button input///////////////////////////////////////////////////////
delay_bars = buy_delay ? 1 : 0

// BARS IN SESSION////////////////////////////////////////////////////////
IsSessionStart(sessionTime, sessionTimeZone=syminfo.timezone) =>
    inSess = not na(time(timeframe.period, sessionTime, sessionTimeZone))
    inSess and not inSess[1]
    
//Verify if the bar happened first in the specified session
isFirstBarOfSession = IsSessionStart(session, timeZone)

//Highlight the first bar of the session with a character
bgcolor(isFirstBarOfSession ? color.new(color.green, 45) : na)

bars_since_session_start = ta.barssince(isNewDay)

//PROFIT CODING///////////////////////////////////////////////////////////////////////
closed_trades_profit = strategy.netprofit[0] - strategy.netprofit[bars_since_session_start]
plot(closed_trades_profit, color=color.rgb(255, 0, 0))

//CLOSED TRADES v OPEN TRADES
max_closed_trades = input.int(1, minval = 1, title = 'Maximun Trades', group = 'Trade Settings', inline = '2')
//max_open_trades = input.int(1, minval = 1, title = 'Maximun Trades', group = 'Trade Settings', inline = '2')

no_closed_trades = strategy.closedtrades[0] - strategy.closedtrades[bars_since_session_start] < max_closed_trades 
no_open_trades = strategy.opentrades[0] - strategy.opentrades[bars_since_session_start] < 1

// Calculate the amount of bars since the last closed trade.
currentBar = bar_index - 4 
lastTradeBarNumber = strategy.closedtrades.exit_bar_index(strategy.closedtrades[bars_since_session_start] - 1)
barsSinceLastTrade = currentBar - lastTradeBarNumber

//MIMIMUN BAR BEFORE NEXT BUY ENTRY
//If last # of X bars have a closed trade = NO entry
bars_before_next_trade = input.int(1, minval = 0, title = 'Bars B4 next Trade', group = 'Next Trade Settings', inline = '2')

// If there are more than zero closed trades/ then bars since last closed trade must be greater than 2 bars
new_closed_trades = delay_next_trade_button ? strategy.closedtrades - strategy.closedtrades[bars_before_next_trade] < 1 : close //? new_trade_delay : close
new_open_trades = delay_next_trade_button ? strategy.opentrades - strategy.opentrades[bars_before_next_trade] < 1 : close //? new_trade_delay : close
required_bars_berfore_entry = new_closed_trades and new_open_trades

//BUY CONDITIONS/////////////////////////////////////////
ott_upper_crs_condition = candle_close >= ott_upper and candle_low <= ott_upper //and ta.rising(ott_upper,1)

rsi_rsiMa_percentage = input.int(10, minval = 3, title = 'Rsi/RsiMa-Percentage', group = 'OTT Settings', inline = '1')
bollinger_percent = input.float(1.0, minval = 0.1, step=0.1, title = 'BB-Percentage', group = 'OTT Settings', inline = '2')

vwap = ta.vwap(hlc3)
vwap_cond = vwap_button ? candle_close >= vwap and candle_open <= vwap : close

ott_rising_buy1 = rsi_abv_percent > rsi_rsiMa_percentage and close > ott_upper and ott_upper_crs_condition and bollinger_abv_percent > bollinger_percent
ott_rising_buy2 = rsi_abv_percent > rsi_rsiMa_percentage and bollinger_abv_percent > bollinger_percent 
ott_rising_buy = ott_rising_button ? (ott_rising_buy1 or ott_rising_buy2) and vwap_cond : close 


//CONDITIONS////////////////////////////////////////////////////////
var new_buy_cond = false
var new_buy = false
new_buy_cond := volume_buy and bar_rising_buy and sma3_buy and new_closed_trades and ott_rising_buy
new_buy := new_buy_cond[delay_bars] and entry_trading_hours_cond

//ENTRY CONDITIONS
long_entry = long_trades and new_buy
long_exit = Sell

var long_price = 0.00
var long_mult = 0.00
var long_profitTarget = 0.00
var long_StopPrice = 0.00
var long_trailStopPrice = 0.00
var long_stop = 0.00

long_price := (strategy.position_size > 0) and (strategy.position_size[1] <= 0) ? open : (strategy.position_size > 0) ? math.max(high,long_price[1]) : na
long_mult := long_price / 100
long_profitTarget := use_profit_target and (strategy.position_size > 0) ? strategy.position_avg_price + ((pt_amount/100) * strategy.position_avg_price) : 99999999
long_StopPrice := strategy.position_avg_price - ((stop_amount/100) * strategy.position_avg_price)
long_trailStopPrice := long_price - trailing_stop_amount * long_mult

if use_stop and use_trailing_stop
    long_stop := math.max(long_StopPrice, long_trailStopPrice)
if use_stop and not use_trailing_stop
    long_stop := long_StopPrice 
if not use_stop and use_trailing_stop
    long_stop := long_trailStopPrice 
if not use_stop and not use_trailing_stop
    long_stop := 0.00

// Plot the Entry bars
barcolor(new_buy_cond and long_trades ? color.new(color.yellow, 10) : na)
bgcolor(new_buy_cond and long_trades and color_trades ? color.new(color.yellow, 60) : na)

//ENTRY ORDERS//////////////////////////////////////////////////////////////
//Limit # of entries AND delay new entries by X # of bars
if required_bars_berfore_entry //limit_number_trades //or new_closed_trades  
    strategy.entry("LE", strategy.long, when = long_entry, comment = "entry", alert_message = "buy") 
  
// EXIT ORDERS///////////////////////////////////////////////////////////////////////
if strategy.position_size > 0 
    strategy.exit(id="LE", limit = long_profitTarget, stop = long_stop, comment = "profit/loss", alert_message = "exit")
    
strategy.close("LE",when = long_exit, comment = "rsi-Ma/exit", alert_message = "exit")

if exit_use_TradingHours and not time("",exit_trading_time, "America/New_York")
    strategy.close_all(comment = 'time/exit', alert_message = "exit")

