// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/

//@version=5
indicator("Xact Breakout Signals", overlay = true, max_lines_count = 500, max_labels_count = 500, max_bars_back = 2000)

// instructions
instructions_tooltip = "The Xact Breakout Signals are designed to catch breakout moves from trend changes.
 \nSignals are displayed above and below candles with a number. The number is our confirmation signals which
 \nact as secondary confirmation to the breakout signals. The confirmations we use are:
 \n\n1. Recent Moving Average Cross
 \n2. Momentum from our Panel
 \n3. Alignment with ORB Strategies
 \n4. Above Normal Volume
 \n5. VWAP (Volume-Weighted Average Price)
 \n6. Moving Average of Your Choice & Timeframe #1
 \n7. Moving Average of Your Choice & Timeframe #2
 \n8. A Secondary Symbols Last Breakout Signal Matches.
 \n\nThat is the base of our signals. Next you can adjust the signals entries, stops, and targets using our adjuster. 
 \nWe did not want to limit the breakout signals to one market so we allow users to tweak the signals to fit their 
 \nmarket, timeframe, and personal risk tolerance."

instructions = input.bool(title='Show Instructions', defval=false, inline='1', tooltip = instructions_tooltip)
var table instruction_label = table.new(position.middle_center, 1, 1,
 frame_color=color.new(#000000, 0), frame_width=0, 
 border_color=color.new(#000000,100), border_width=0)
if barstate.islast and instructions
    table.cell(instruction_label, 0, 0, text=instructions_tooltip, width=0, 
     bgcolor=color.black, text_color=color.white, text_size=size.normal, text_halign=text.align_left)



// signal settings
trend_adj       = input.int(title='Signal Adjuster  ', defval=10, minval=1, maxval=25, step=1,
 inline='4', group='Breakout Signal Settings', 
 tooltip = "Recommended Settings: \nExtreme Scalping: 1-5 \nScalping: 5-10 \nIntra-day: 10-15 \nSwing: 15+")

target_adj      = input.float(title='Target Adjuster ', defval=1.0, minval=1, maxval=10, step=0.25,
 inline='5', group='Breakout Signal Settings', 
 tooltip = "Recommended Settings: \nScalping: 1-3 \nIntra-day: 4-7 \nSwing: 7-10")

stop_adj        = input.float(title='Stop Adjuster  ', defval=1.0, minval=1, maxval=10, step=0.25,
 inline='6', group='Breakout Signal Settings',
 tooltip = "Recommended Settings: \nScalping: 1-3 \nIntra-day: 4-7 \nSwing: 7-10")



// visual settings
show_signals    = input.bool(title='Buy/Sell Signals', defval=true,
 inline='1', group='Visual Settings',
 tooltip = "The Buy/Sell Signals are a breakout algorithm that capture when markets 
 are breaking out of support or resistance.")

use_reentry     = input.bool(title = 'Re-entry Signals', defval=false,
 inline='2', group='Visual Settings',
 tooltip = "The Re-Entry Signal is a small triangle that appears when the logic for re-entry is 
 deemed true by the algorithm. Note that if this box is checked it does 
 not adjust the main signals entry, target, or stop lines.")

show_cloud      = input.bool(title='Xact Cloud', defval=true,
 inline='3', group='Visual Settings',
 tooltip = 'The Xact Cloud is part of the algorithm, but it is not all of the secret sauce for signals.
 The Cloud can be used to tell you the current trend and also act as an adaptive moving for pullbacks.')

show_scalp      = input.bool(title='Xact Scalping Channel', defval=false,
 inline='4', group='Visual Settings',
 tooltip = 'The Xact Scalping Channel is used for alternate scalping entries after a signal has been
 placed on the chart. The channel can also be used for take profits.')

show_tp_labels  = input.bool(title='Target Hit Labels', defval=false,
 inline='5', group='Visual Settings')

showing_lines   = input.string(defval = "No Lines", title='Trade Management Lines',
 options =["Current Signal Only", "All Signals (Backtesting)", "No Lines"],
  inline='6', group='Visual Settings')

show_pos_lines  = showing_lines != "No Lines" ? true : false
show_backtest   = showing_lines == "All Signals (Backtesting)" ? true : false

buy_color       = input.color(#05cd0e, title='Buy  ', inline='9', group='Visual Settings')
sell_color      = input.color(#c30616, title='Sell   ', inline='9', group='Visual Settings')
entry_color     = input.color(title='Entry', defval=color.new(color.blue, 0), inline='10', group='Visual Settings')
tgts_color      = input.color(title='Targets', defval=color.new(#abf3ae, 0), inline='10', group='Visual Settings')
stop_color      = input.color(title='Stop', defval=color.new(#feadcf, 0), inline='10', group='Visual Settings')
tgthit_color    = chart.fg_color
c_color         = chart.fg_color



// confirmation settings
_use_confirmation_signals = input.bool(true, title = 'Confirmation Signals',
 group = 'Confirmation Signals', inline = '0')

c_2nd_symbol        = input.symbol('BATS:SPY', title = 'Secondary Symbol  ',
 group = 'Confirmation Signals', inline = '1',
 tooltip = 'A Confirmation if this symbol and the Chart have the same signal')

c_momo_length = input.int(20, title = 'Momentum        ',
 minval = 10, maxval = 200, step = 1,
 group = 'Confirmation Signals', inline = '2',
 tooltip = '(Calculation from Xact Panel) \nFor Buy Signals - Panel is green \nFor Sell Signals - Panel is red')

c_ma1_length = input.int(defval=50, title='MA 1',
 minval = 10, maxval = 200, step = 1,
 group = 'Confirmation Signals', inline = '3',
 tooltip = 'For Buy Signals - Price is above this Moving Average \nFor Sell Signals - Price is below this Moving Average')
c_ma1_type = input.string(title=' ', defval='EMA',
 options=['MA', 'WMA', 'VWMA', 'EMA', 'HMA'],
 group = 'Confirmation Signals', inline = '3')
c_ma1_tf = input.timeframe(title=' ', defval='',
 group = 'Confirmation Signals', inline = '3')

c_ma2_length = input.int(defval=20, title='MA 2',
 minval = 10, maxval = 200, step = 1,
 group = 'Confirmation Signals', inline = '4',
 tooltip = 'For Buy Signals - Price is above this Moving Average \nFor Sell Signals - Price is below this Moving Average')
c_ma2_type = input.string(title=' ', defval='EMA',
 options=['MA', 'WMA', 'VWMA', 'EMA', 'HMA'],
 group = 'Confirmation Signals', inline = '4')
c_ma2_tf = input.timeframe(title='', defval='D',
 group = 'Confirmation Signals', inline = '4')





// signal logic
get_trend(symbol, trend_adj, use_reentry) =>

    //base logic
    trend_length = 4 * trend_adj
    
    //call base trend function
    trend_breakout = request.security(symbol, "" , barstate.isconfirmed 
     and (ta.rsi(close,14) > 60 or ta.rsi(close,14) < 40) 
     and close > (ta.ema(hlc3,trend_length) + (ta.stdev(ta.ema(hlc3,trend_length),trend_length) * (0.25 * trend_adj)))  
     and  low > ta.ema(hlc3,trend_length) and high >= ta.highest(high, trend_length))
     
    trend_breakdown = request.security(symbol, "" , barstate.isconfirmed 
     and (ta.rsi(close,14) > 60 or ta.rsi(close,14) < 40) 
     and close < (ta.ema(hlc3,trend_length) - (ta.stdev(ta.ema(hlc3,trend_length),trend_length) * (0.25 * trend_adj))) 
     and high < ta.ema(hlc3,trend_length) and low <= ta.lowest(low, trend_length))
    
    //plotting only for signals can be removed for scanner
    trend_avg = ta.ema(hlc3,trend_length)
    trend_stddev = ta.stdev(ta.ema(hlc3,trend_length),trend_length)
    
    //base trend direction
    var trend_direction = 0
    trend_direction := trend_breakout ? 1 : trend_breakdown ? -1 : trend_direction[1]
    
    var base_color = #000000
    base_color := trend_direction == 1 ? buy_color : trend_direction == -1 ? sell_color : na   
    
    //OUTPUT with or without filtering
    var long_entry = false
    var long_exit = false
    var short_entry = false
    var short_exit = false
      
    long_entry := trend_direction == 1 and trend_direction[1] == -1
    long_exit := false
    short_entry := trend_direction == -1 and trend_direction[1] == 1
    short_exit := false
    
    //RE-ENTRY  
    var last_entry_bn = 0
    var re_entry_count = 0
    var long_reentry = false
    var short_reentry = false
    last_entry_bn := (long_entry == true or short_entry == true)  ? 1 : last_entry_bn[1] + 1
    re_entry_count := (long_entry == true or short_entry == true) ? 1 : re_entry_count[1]
    
    var crossover = false
    var crossunder = false
    crossover := ta.crossover(close, trend_avg)
    crossunder := ta.crossunder(close, trend_avg)
    
    if use_reentry and barstate.isconfirmed 
        if trend_direction == 1 and last_entry_bn >= 20 and re_entry_count == 1 and crossover
            long_reentry := true
            re_entry_count := re_entry_count[1] + 1
        else if trend_direction == -1 and last_entry_bn >= 20 and re_entry_count == 1 and crossunder
            short_reentry := true
            re_entry_count := re_entry_count[1] + 1            
        else
            long_reentry := false
            short_reentry := false
                
    
    [trend_avg, trend_stddev, trend_direction, long_entry, long_exit, short_entry, short_exit, long_reentry, short_reentry, base_color]

[trend_avg, trend_stddev, trend_direction, long_entry, long_exit, short_entry, short_exit, long_reentry, short_reentry, base_color] = 
 get_trend(syminfo.tickerid, trend_adj, use_reentry)



// calculate strategy
entry = 0.00
stop = 0.00
risk_baseline = 0.00
tgt1 = 0.00
tgt2 = 0.00
tgt3 = 0.00
tgt4 = 0.00
tgt5 = 0.00
var bool hit_tgt1 = false
var bool hit_tgt2 = false
var bool hit_tgt3 = false
var bool hit_tgt4 = false
var bool hit_tgt5 = false
entry_bn = 0
var float label_yaxis = 0.00
trend_atr = ta.atr(4 * trend_adj)
trend_cloudlow = trend_avg - trend_stddev * 0.25
trend_cloudhigh = trend_avg + trend_stddev * 0.25

if trend_direction == 1
    if long_entry
        entry := close
        stop := entry - stop_adj * trend_atr
        risk_baseline := entry - (entry - target_adj * trend_atr)
        tgt1 := entry + risk_baseline
        tgt2 := entry + risk_baseline * 2
        tgt3 := entry + risk_baseline * 3
        tgt4 := entry + risk_baseline * 4
        tgt5 := entry + risk_baseline * 5
        hit_tgt1 := false
        hit_tgt2 := false
        hit_tgt3 := false
        hit_tgt4 := false
        hit_tgt5 := false
        entry_bn := time
        label_yaxis := math.min(low, trend_cloudlow) - syminfo.mintick * 10
    else
        entry := entry[1]
        stop := stop[1]
        risk_baseline := risk_baseline[1]
        tgt1 := tgt1[1]
        tgt2 := tgt2[1]
        tgt3 := tgt3[1]
        tgt4 := tgt4[1]
        tgt5 := tgt5[1]
        hit_tgt1 := not hit_tgt1[1] and high > tgt1 ? true : hit_tgt1[1]
        hit_tgt2 := not hit_tgt2[1] and high > tgt2 ? true : hit_tgt2[1]
        hit_tgt3 := not hit_tgt3[1] and high > tgt3 ? true : hit_tgt3[1]
        hit_tgt4 := not hit_tgt4[1] and high > tgt4 ? true : hit_tgt4[1]
        hit_tgt5 := not hit_tgt5[1] and high > tgt5 ? true : hit_tgt5[1]
        entry_bn := entry_bn[1]
        label_yaxis := math.min(low, trend_cloudlow) - syminfo.mintick * 10


if trend_direction == -1
    if short_entry
        entry := close
        stop := entry + stop_adj * trend_atr
        risk_baseline :=(entry + target_adj * trend_atr) - entry
        tgt1 := entry - risk_baseline
        tgt2 := entry - risk_baseline * 2
        tgt3 := entry - risk_baseline * 3
        tgt4 := entry - risk_baseline * 4
        tgt5 := entry - risk_baseline * 5
        hit_tgt1 := false
        hit_tgt2 := false
        hit_tgt3 := false
        hit_tgt4 := false
        hit_tgt5 := false
        entry_bn := bar_index
        label_yaxis := math.max(high, trend_cloudhigh) + syminfo.mintick * 10
    else
        entry := entry[1]
        stop := stop[1]
        risk_baseline := risk_baseline[1]
        tgt1 := tgt1[1]
        tgt2 := tgt2[1]
        tgt3 := tgt3[1]
        tgt4 := tgt4[1]
        tgt5 := tgt5[1]
        hit_tgt1 := not hit_tgt1[1] and low < tgt1 ? true : hit_tgt1[1]
        hit_tgt2 := not hit_tgt2[1] and low < tgt2 ? true : hit_tgt2[1]
        hit_tgt3 := not hit_tgt3[1] and low < tgt3 ? true : hit_tgt3[1]
        hit_tgt4 := not hit_tgt4[1] and low < tgt4 ? true : hit_tgt4[1]
        hit_tgt5 := not hit_tgt5[1] and low < tgt5 ? true : hit_tgt5[1]
        entry_bn := entry_bn[1]
        label_yaxis := math.max(high, trend_cloudhigh) + syminfo.mintick * 10




// calculate confirmation
var float   second_signal   =   na
var string  second_ticker   =   str.substring(c_2nd_symbol, str.pos(c_2nd_symbol, ":")+1)
var float   momo_value      =   na
var float   ma1_value       =   na
var float   ma2_value       =   na


f_momo() =>
    [ha_o, ha_c, ha_h, ha_l] = request.security(ticker.heikinashi(syminfo.tickerid), timeframe.period, 
     [ta.ema(open, c_momo_length), ta.ema(close, c_momo_length), 
     ta.ema(high, c_momo_length), ta.ema(low, c_momo_length)])

    ha_o_smooth = ta.ema(ha_o, c_momo_length)
    ha_c_smooth = ta.ema(ha_c, c_momo_length)
    ha_h_smooth = ta.ema(ha_h, c_momo_length)
    ha_l_smooth = ta.ema(ha_l, c_momo_length)
    dif_oc = ha_c_smooth - ha_o_smooth
    dif_hl = ha_h_smooth - ha_l_smooth
    variable_oc_percent =  math.round(dif_oc * 100 / dif_hl,1)


f_ma(ma_type, ma_tf, ma_length) =>
    math.round_to_mintick(request.security(syminfo.ticker, ma_tf, 
     ma_type == 'EMA' ? ta.ema(close[1], ma_length) :
     ma_type == 'MA' ? ta.sma(close[1], ma_length) :
     ma_type == 'WMA' ? ta.wma(close[1], ma_length) :
     ma_type == 'VWMA' ? ta.vwma(close[1], ma_length) :
     ma_type == 'HMA' ? ta.hma(close[1], ma_length)
     : ta.sma(close[1], ma_length),
     lookahead = barmerge.lookahead_on))


f_display_confirmations(signal_type,
 second_signal,
 momo_value,
 ma1_value,
 ma2_value,
 y_axis) =>

    confirmation1_value = ((signal_type == 1 and second_signal == 1) or (signal_type and second_signal == -1)) ? 1 : 0
    confirmation2_value = ((signal_type == 1 and momo_value > 0) or (signal_type and momo_value < 0)) ? 1 : 0
    confirmation3_value = ((signal_type == 1 and close > ma1_value) or (signal_type and close < ma1_value)) ? 1 : 0
    confirmation4_value = ((signal_type == 1 and close > ma2_value) or (signal_type and close < ma2_value)) ? 1 : 0

    confirmation_values = confirmation1_value + confirmation2_value + confirmation3_value + confirmation4_value
    
    confirmation_tooltip =  
     ( (confirmation1_value == 1 ? '✅' : '❌') + ' ' + second_ticker + (confirmation1_value == 1 ? ' - Signal Matches' : ' - Signal Does Not Match') ) + 
     '\n' +
     ( (confirmation2_value == 1 ? '✅' : '❌') + ' MOMO PANEL - ' + str.tostring(momo_value) ) +
     '\n' +
     ( (confirmation3_value == 1 ? '✅' : '❌') + ' MA1 - ' + str.tostring(ma1_value) ) + 
     '\n' +
     ( (confirmation4_value == 1 ? '✅' : '❌') + ' MA2 - ' + str.tostring(ma2_value) )+
     '\n\nCONFIRMED: ' + str.tostring(confirmation_values) + '/4'

    if signal_type == 1
        label.new( x = bar_index, y = y_axis, text = '\n' + str.tostring(confirmation_values) + '/4',
         textcolor = chart.fg_color, color = color.new(buy_color, 100), style = label.style_label_up, 
         size = size.small, tooltip = confirmation_tooltip, textalign = text.align_center)
    
    else if signal_type == -1
        label.new( x = bar_index, y = y_axis, text = str.tostring(confirmation_values) + '/4',
         textcolor = chart.fg_color, color = color.new(sell_color, 100), style = label.style_triangledown, 
         size = size.small, tooltip = confirmation_tooltip, textalign = text.align_center)


if _use_confirmation_signals
    [c_trend_avg, c_trend_stddev, c_trend_direction, c_long_entry, c_long_exit, c_short_entry, c_short_exit, c_long_reentry, c_short_reentry, c_base_color] = 
     get_trend(c_2nd_symbol, trend_adj, use_reentry)
    second_signal := c_long_entry ? 1 : c_short_entry ? -1 : second_signal[1]

    momo_value := f_momo()
    ma1_value := f_ma(c_ma1_type, c_ma1_tf, c_ma1_length)
    ma2_value := f_ma(c_ma2_type, c_ma2_tf, c_ma2_length)

    if long_entry
        f_display_confirmations(1,
         second_signal,
         momo_value,
         ma1_value,
         ma2_value,
         label_yaxis)

    if short_entry
        f_display_confirmations(-1,
         second_signal,
         momo_value,
         ma1_value,
         ma2_value,
         label_yaxis)



// visualise tp labels
var bool tp_hit = false
if show_signals and show_tp_labels
    ylocation = trend_direction == 1 ? yloc.abovebar : trend_direction == -1 ? yloc.belowbar : yloc.price
    label_text = hit_tgt5 and not hit_tgt5[1] ? '5'
     : hit_tgt4 and not hit_tgt4[1] ? '4'
     : hit_tgt3 and not hit_tgt3[1] ? '3'
     : hit_tgt2 and not hit_tgt2[1] ? '2'
     : hit_tgt1 and not hit_tgt1[1] ? '1'
     : ''
    tp_hit := (hit_tgt1 and not hit_tgt1[1])
     or (hit_tgt2 and not hit_tgt2[1])
     or (hit_tgt3 and not hit_tgt3[1])
     or (hit_tgt4 and not hit_tgt4[1])
     or (hit_tgt5 and not hit_tgt5[1])

    if tp_hit
        label.new(time, close, text = label_text, xloc = xloc.bar_time, yloc = ylocation, size = size.small,
         color = color.new(color.black,100), textcolor = chart.fg_color, style = label.style_none)



// visualize position lines
var entry_lines = array.new_line(50, na)
var tp1_lines   = array.new_line(50, na)
var tp2_lines   = array.new_line(50, na)
var tp3_lines   = array.new_line(50, na)
var tp4_lines   = array.new_line(50, na)
var tp5_lines   = array.new_line(50, na)
var sl_lines    = array.new_line(50, na)

if show_pos_lines
    if long_entry or short_entry
        if not show_backtest
            line.delete(array.last(entry_lines))
            line.delete(array.last(tp1_lines))
            line.delete(array.last(tp2_lines))
            line.delete(array.last(tp3_lines))
            line.delete(array.last(tp4_lines))
            line.delete(array.last(tp5_lines))
            line.delete(array.last(sl_lines))
        else
            line.set_extend(array.last(entry_lines), extend.none)
            line.set_extend(array.last(tp1_lines), extend.none)
            line.set_extend(array.last(tp2_lines), extend.none)
            line.set_extend(array.last(tp3_lines), extend.none)
            line.set_extend(array.last(tp4_lines), extend.none)
            line.set_extend(array.last(tp5_lines), extend.none)
            line.set_extend(array.last(sl_lines), extend.none)

        array.push(entry_lines, line.new(time, entry, time + 1, entry, xloc = xloc.bar_time,
         extend = extend.right, color = entry_color, style = line.style_solid, width = 1))
        array.push(tp1_lines, line.new(time, tgt1, time + 1, tgt1, xloc = xloc.bar_time,
         extend = extend.right, color = tgts_color, style = line.style_solid, width = 1))
        array.push(tp2_lines, line.new(time, tgt2, time + 1, tgt2, xloc = xloc.bar_time,
         extend = extend.right, color = tgts_color, style = line.style_solid, width = 1))
        array.push(tp3_lines, line.new(time, tgt3, time + 1, tgt3, xloc = xloc.bar_time,
         extend = extend.right, color = tgts_color, style = line.style_solid, width = 1))
        array.push(tp4_lines, line.new(time, tgt4, time + 1, tgt4, xloc = xloc.bar_time,
         extend = extend.right, color = tgts_color, style = line.style_solid, width = 1))
        array.push(tp5_lines, line.new(time, tgt5, time + 1, tgt5, xloc = xloc.bar_time,
         extend = extend.right, color = tgts_color, style = line.style_solid, width = 1))
        array.push(sl_lines, line.new(time, stop, time + 1, stop, xloc = xloc.bar_time,
         extend = extend.right, color = stop_color, style = line.style_solid, width = 1))

    line.set_x2(array.last(entry_lines), time)
    line.set_x2(array.last(tp1_lines), time)
    line.set_x2(array.last(tp2_lines), time)
    line.set_x2(array.last(tp3_lines), time)
    line.set_x2(array.last(tp4_lines), time)
    line.set_x2(array.last(tp5_lines), time)
    line.set_x2(array.last(sl_lines), time)



// visualize trend cloud
trend_fill_high = plot(show_cloud ? trend_cloudhigh : na, title='Cloud High',
 color=color.new(color.white, 100), editable=false)
trend_fill_low = plot(show_cloud ? trend_cloudlow : na, title='Cloud Low',
 color=color.new(color.white, 100), editable=false)

trend_high_shade = plot(show_cloud ? trend_cloudhigh + trend_atr * .1 : na, title='Cloud High',
 color=color.new(#c2c2c2, 90), editable=false)
trend_low_shade = plot(show_cloud ? trend_cloudlow - trend_atr * .1 : na, title='Cloud Low',
 color=color.new(#c2c2c2, 90), editable=false)
 
fill(trend_fill_high, trend_fill_low, editable=false, color=color.new(base_color, 60), title='Cloud')
fill(trend_high_shade, trend_low_shade, editable=false, color=color.new(base_color, 85), title='Cloud')



// visualize signals
plotshape(show_signals and long_entry ? label_yaxis : na, style=shape.labelup, editable=false,
 text= "BUY", textcolor=color.white, location= location.absolute, color=color.new(buy_color, 30), size=size.tiny)
plotshape(show_signals and short_entry ? label_yaxis : na, style=shape.labeldown, editable=false,
 text='SELL', textcolor=color.white, location=location.absolute, color=color.new(sell_color, 30), size=size.tiny)

plotshape(show_signals and short_exit ? label_yaxis : na, style=shape.labelup, editable=false,
 text= "Exit", textcolor=color.white, location= location.absolute, color=color.new(buy_color, 30), size=size.tiny)
plotshape(show_signals and long_exit ? label_yaxis : na, style=shape.labeldown, editable=false, 
 text='Exit', textcolor=color.white, location=location.absolute, color=color.new(sell_color, 30), size=size.tiny)

plotshape(show_signals and long_reentry ? label_yaxis : na, style=shape.labelup, editable=false,
 text= 'Re-E', textcolor=color.white, location= location.absolute, color=color.new(buy_color, 70), size=size.tiny)
plotshape(show_signals and short_reentry ? label_yaxis : na, style=shape.labeldown, editable=false,
 text='Re-E', textcolor=color.white, location=location.absolute, color=color.new(sell_color, 70), size=size.tiny)



// visualized scalping channel
f_calculate_linreg(source, length, deviation1, deviation2) =>

    var line upper1 = na
    var line upper2 = na
    var line mid    = na
    var line lower1 = na
    var line lower2 = na

    if show_scalp
        a = ta.wma(source, length)
        b = ta.sma(source, length)

        if barstate.islast
            A = 4 * b - 3 * a
            B = 3 * a - 2 * b
            m = (A - B) / (length - 1)
            
            d = 0.00
            for i = 0 to length - 1 by 1
                l = B + m * i
                d += math.pow(source[i] - l, 2)
                d
            linreg_1 = math.sqrt(d / (length - 1)) * deviation1
            linreg_2 = math.sqrt(d / (length - 1)) * deviation2

            // mid 
            y1_midvalue = A + 0
            y2_midvalue = -m + (B + 0)
            
            // zone 1
            y1_lowervalue = A - linreg_1
            y2_lowervalue = -m + (B - linreg_1)
            y1_uppervalue = A + linreg_1
            y2_uppervalue = -m + (B + linreg_1)

            // zone 2
            y1_lowervalue2 = A - linreg_2
            y2_lowervalue2 = -m + (B - linreg_2)
            y1_uppervalue2 = A + linreg_2
            y2_uppervalue2 = -m + (B + linreg_2)

            x1_value = time[length]    

            if na(mid[1])
                mid := line.new(x1_value, y1_midvalue, time, y2_midvalue, xloc = xloc.bar_time,
                 extend = extend.right, color = color.new(chart.fg_color,50), width = 1, style = line.style_dotted)

                upper1 := line.new(x1_value, y1_uppervalue, time, y2_uppervalue, xloc = xloc.bar_time,
                 extend = extend.right, color = color.new(sell_color,50), width = 1, style = line.style_solid)
                upper2 := line.new(x1_value, y1_uppervalue2, time, y2_uppervalue2, xloc = xloc.bar_time,
                 extend = extend.right, color = color.new(sell_color,50), width = 1, style = line.style_solid)

                lower1 := line.new(x1_value, y1_lowervalue, time, y2_lowervalue, xloc = xloc.bar_time,
                 extend = extend.right, color = color.new(buy_color,50), width = 1, style = line.style_solid)
                lower2 := line.new(x1_value, y1_lowervalue2, time, y2_lowervalue2, xloc = xloc.bar_time,
                 extend = extend.right, color = color.new(buy_color,50), width = 1, style = line.style_solid)
            else if barstate.isconfirmed
                line.set_xy1(mid, x1_value, y1_midvalue)
                line.set_xy2(mid, time, y2_midvalue)
                
                line.set_xy1(upper1, x1_value, y1_uppervalue)
                line.set_xy2(upper1, time, y2_uppervalue)
                line.set_xy1(upper2, x1_value, y1_uppervalue2)
                line.set_xy2(upper2, time, y2_uppervalue2)

                line.set_xy1(lower1, x1_value, y1_lowervalue)
                line.set_xy2(lower1, time, y2_lowervalue)
                line.set_xy1(lower2, x1_value, y1_lowervalue2)
                line.set_xy2(lower2, time, y2_lowervalue2)
        0.00


var int bars_since_last_signal = 20
bars_since_last_signal := long_entry or short_entry ? 1 : bars_since_last_signal[1] + 1
f_calculate_linreg(hlc3, math.min(nz(math.max(bars_since_last_signal,20),20), 2000), 2.5, 3.5)



// [x1_value,
//  y1_midvalue, y2_midvalue,
//  y1_lowervalue, y2_lowervalue,
//  y1_lowervalue2, y2_lowervalue2] = f_calculate_linreg(hlc3, 100, 2.0, 3.0)

// var line temp_line = na
// if na(temp_line[1])
//     temp_line := line.new(x1_value, y1_lowervalue, time, y2_lowervalue2, xloc = xloc.bar_time,
//      extend = extend.right, color = color.new(color.yellow,0), width = 5, style = line.style_solid)
// else
//     line.set_xy1(temp_line, x1_value, y1_lowervalue)
//     line.set_xy2(temp_line, time, y1_lowervalue2)

// alerts
alertcondition(long_entry, "Long Entry", "Long Entry")
alertcondition(short_entry, "Short Entry", "Short Entry")

alertcondition(long_reentry, "Long Re-Entry", "Long Re-Entry")
alertcondition(short_reentry, "Short Re-Entry", "Short Re-Entry")

alertcondition(long_exit, "Long Exit", "Long Exit")
alertcondition(short_exit, "Short Exit", "Short Exit")
